Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'ResearchIntakePersistence.psm1') -Force

function Copy-RapIntakeValue { param([AllowNull()]$Value) if($null-eq$Value){return $null};$Value|ConvertTo-Json -Depth 60|ConvertFrom-Json -Depth 60 }
function Get-RapIntakeHash { param([AllowNull()]$Value) $json=$Value|ConvertTo-Json -Depth 60 -Compress;[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($json))).ToLowerInvariant() }
function Assert-RapProjectId { param([string]$ProjectId) if($ProjectId-notmatch'^PR\d{3,6}$'){throw 'PROJECT_CONTEXT_AMBIGUOUS'} }
function Add-RapIntakeAudit { param($Store,[string]$Event,[string]$State,[hashtable]$Data) $entry=[pscustomobject][ordered]@{Sequence=$Store.Audit.Count+1;Event=$Event;State=$State;Timestamp=[DateTimeOffset]::UtcNow.ToString('o');Data=[pscustomobject]$Data;ProductionWrite='DISABLED'};$Store.Audit.Add($entry);if($Store.DatabasePath){[void](Save-RapResearchIntakeStore $Store)};$entry }
function Get-RapProperty { param($Object,[string]$Name) if($null-ne$Object-and$Object.PSObject.Properties[$Name]){$Object.$Name}else{$null} }
function Normalize-RapText { param([AllowNull()][string]$Text) if([string]::IsNullOrWhiteSpace($Text)){return ''};(($Text.Trim().ToLowerInvariant()-replace'[^\p{L}\p{Nd}]+',' ') -replace'\s+',' ').Trim() }
function Normalize-RapDoi {
    param([AllowNull()][string]$Doi)
    if([string]::IsNullOrWhiteSpace($Doi)){return $null}
    $value=$Doi.Trim().ToLowerInvariant()
    $value=$value-replace'^doi\s*:\s*',''
    $value=$value-replace'^https?://(dx\.)?doi\.org/',''
    $value=$value.Trim()
    if($value-notmatch'^10\.\d{4,9}/[-._;()/:a-z0-9]+$'-or$value-match'\s'){throw 'INVALID_DOI'}
    $value
}
function Get-RapMetadataSignature { param($Paper) "$(Normalize-RapText ([string](Get-RapProperty $Paper 'Title')))|$(Normalize-RapText ([string](Get-RapProperty $Paper 'FirstAuthor')))|$([string](Get-RapProperty $Paper 'Year'))" }
function Test-RapStrongMetadataConflict { param($A,$B) $titleA=Normalize-RapText ([string](Get-RapProperty $A 'Title'));$titleB=Normalize-RapText ([string](Get-RapProperty $B 'Title'));$authorA=Normalize-RapText ([string](Get-RapProperty $A 'FirstAuthor'));$authorB=Normalize-RapText ([string](Get-RapProperty $B 'FirstAuthor'));$yearA=[string](Get-RapProperty $A 'Year');$yearB=[string](Get-RapProperty $B 'Year');($titleA-and$titleB-and$titleA-cne$titleB)-or($authorA-and$authorB-and$authorA-cne$authorB)-or($yearA-and$yearB-and$yearA-cne$yearB) }
function Get-RapCandidateIdentitySnapshot { param($Candidate) [ordered]@{ProjectId=$Candidate.ProjectId;ResearchQuestionId=$Candidate.ResearchQuestionId;SearchExecutionId=$Candidate.SearchExecutionId;SearchMode=$Candidate.SearchMode;CandidateId=$Candidate.CandidateId;Title=$Candidate.Title;FirstAuthor=$Candidate.FirstAuthor;Year=$Candidate.Year;Doi=$Candidate.Doi;Pmid=$Candidate.Pmid;Pmcid=$Candidate.Pmcid;PublisherId=$Candidate.PublisherId;Source=$Candidate.Source;SearchProvenance=$Candidate.SearchProvenance} }
function Get-RapPromotionBinding { param($Promotion) $promotedAt=[DateTimeOffset]::Parse([string]$Promotion.PromotedAt,[Globalization.CultureInfo]::InvariantCulture).ToUniversalTime().ToString('o');[ordered]@{ProjectId=$Promotion.ProjectId;ResearchQuestionId=$Promotion.ResearchQuestionId;SearchExecutionId=$Promotion.SearchExecutionId;SearchMode=$Promotion.SearchMode;SearchSource=$Promotion.SearchSource;SearchProvenance=$Promotion.SearchProvenance;CandidateId=$Promotion.CandidateId;CandidateIdentityHash=$Promotion.CandidateIdentityHash;Researcher=$Promotion.Researcher;Provenance=$Promotion.Provenance;PromotedAt=$promotedAt} }
function Assert-RapPromotionBinding { param($Store,$Promotion)
    if($Promotion.PSObject.TypeNames-cnotcontains'Rap.ResearchPromotion'-or-not$Store.Promotions.ContainsKey($Promotion.CandidateId)){throw 'UNTRUSTED_PROMOTION'}
    $persisted=$Store.Promotions[$Promotion.CandidateId];if($persisted.PromotionHash-cne$Promotion.PromotionHash-or(Get-RapIntakeHash (Get-RapPromotionBinding $persisted))-cne$persisted.PromotionHash){throw 'PROMOTION_BINDING_MISMATCH'}
    if(-not$Store.Inbox.ContainsKey($Promotion.CandidateId)){throw 'CANDIDATE_SUBSTITUTION'};$candidate=$Store.Inbox[$Promotion.CandidateId]
    if((Get-RapIntakeHash (Get-RapCandidateIdentitySnapshot $candidate))-cne$persisted.CandidateIdentityHash){throw 'CANDIDATE_SUBSTITUTION'}
    foreach($name in @('ProjectId','ResearchQuestionId','SearchExecutionId','SearchMode','CandidateId')){if([string]$candidate.$name-cne[string]$persisted.$name){throw 'CANDIDATE_SUBSTITUTION'}}
    $persisted
}
function Get-RapIdentityEvidenceHash { param($Identity) Get-RapIntakeHash ([ordered]@{CandidateId=$Identity.CandidateId;ProjectId=$Identity.ProjectId;ResearchQuestionId=$Identity.ResearchQuestionId;Status=$Identity.Status;Authority=$Identity.Authority;CanonicalKey=$Identity.CanonicalKey;NormalizedDoi=$Identity.NormalizedDoi;Pmid=$Identity.Pmid;Pmcid=$Identity.Pmcid;PublisherId=$Identity.PublisherId;MetadataSignature=$Identity.MetadataSignature;Evidence=@($Identity.Evidence)}) }
function Get-RapIdentityBinding { param($Identity) [ordered]@{BindingVersion=$Identity.IdentityBindingVersion;IdentityId=$Identity.IdentityId;ProjectId=$Identity.ProjectId;ResearchQuestionId=$Identity.ResearchQuestionId;SearchExecutionId=$Identity.SearchExecutionId;CandidateId=$Identity.CandidateId;PromotionHash=$Identity.PromotionHash;CandidateIdentityHash=$Identity.CandidateIdentityHash;ObservedDoi=$Identity.ObservedDoi;ObservedPmid=$Identity.ObservedPmid;ObservedPmcid=$Identity.ObservedPmcid;ObservedPublisherId=$Identity.ObservedPublisherId;Title=$Identity.Title;FirstAuthor=$Identity.FirstAuthor;Year=$Identity.Year;Status=$Identity.Status;Authority=$Identity.Authority;CanonicalKey=$Identity.CanonicalKey;NormalizedDoi=$Identity.NormalizedDoi;Pmid=$Identity.Pmid;Pmcid=$Identity.Pmcid;PublisherId=$Identity.PublisherId;MetadataSignature=$Identity.MetadataSignature;Evidence=@($Identity.Evidence);ResolvedAt=$Identity.ResolvedAt;Provenance=$Identity.Provenance;ProductionWrite=$Identity.ProductionWrite} }
function Assert-RapIdentityAuthority { param($Store,$Promotion,$Identity)
    if(-not$Store.IdentityResults.ContainsKey($Promotion.CandidateId)){throw 'IDENTITY_AUTHORITY_MISSING'};$stored=$Store.IdentityResults[$Promotion.CandidateId]
    foreach($name in @('IdentityBindingVersion','IdentityId','ProjectId','ResearchQuestionId','SearchExecutionId','CandidateId','PromotionHash','CandidateIdentityHash','IdentityBindingHash','ResolvedAt')){if(-not$stored.PSObject.Properties[$name]){throw 'IDENTITY_AUTHORITY_INVALID'}}
    $storedHash=Get-RapIntakeHash (Get-RapIdentityBinding $stored);if($storedHash-cne$stored.IdentityBindingHash){throw 'IDENTITY_BINDING_MISMATCH'}
    if($stored.ProjectId-cne$Promotion.ProjectId-or$stored.ResearchQuestionId-cne$Promotion.ResearchQuestionId-or$stored.SearchExecutionId-cne$Promotion.SearchExecutionId-or$stored.CandidateId-cne$Promotion.CandidateId-or$stored.PromotionHash-cne$Promotion.PromotionHash){throw 'IDENTITY_BINDING_MISMATCH'}
    if($null-eq$Identity-or-not$Identity.PSObject.Properties['IdentityBindingHash']-or(Get-RapIntakeHash (Get-RapIdentityBinding $Identity))-cne$Identity.IdentityBindingHash-or$Identity.IdentityBindingHash-cne$stored.IdentityBindingHash){throw 'IDENTITY_BINDING_MISMATCH'}
    $stored
}
function Get-RapLookupEvidenceHash { param($Store,$Identity) Get-RapIntakeHash ([ordered]@{CandidateId=$Identity.CandidateId;CanonicalKey=$Identity.CanonicalKey;Snapshot=$Store.LookupSnapshot;CanonicalPapers=@($Store.CanonicalPapers);ZoteroItems=@($Store.ZoteroItems)}) }
function Get-RapDecisionBinding { param($Decision) [ordered]@{BindingVersion=$Decision.BindingVersion;DecisionId=$Decision.DecisionId;ProjectId=$Decision.ProjectId;ResearchQuestionId=$Decision.ResearchQuestionId;SearchExecutionId=$Decision.SearchExecutionId;CandidateId=$Decision.CandidateId;PromotionHash=$Decision.PromotionHash;CandidateIdentityHash=$Decision.CandidateIdentityHash;IdentityBindingHash=$Decision.IdentityBindingHash;IdentityEvidenceHash=$Decision.IdentityEvidenceHash;CanonicalKey=$Decision.CanonicalKey;CanonicalTargetIdentity=$Decision.CanonicalTargetIdentity;ZoteroItemId=$Decision.ZoteroItemId;ZoteroLibraryContext=$Decision.ZoteroLibraryContext;ExactTargetEvidenceHash=$Decision.ExactTargetEvidenceHash;LookupExecutionId=$Decision.LookupExecutionId;LookupEvidenceHash=$Decision.LookupEvidenceHash;CanonicalStatus=$Decision.CanonicalStatus;ZoteroStatus=$Decision.ZoteroStatus;CanonicalMatches=$Decision.CanonicalMatches;ZoteroMatches=$Decision.ZoteroMatches;Decision=$Decision.Decision;Reason=$Decision.Reason;State=$Decision.State;RevalidationSequence=$Decision.RevalidationSequence;RevalidationEvidenceHash=$Decision.RevalidationEvidenceHash;DecidedAt=$Decision.DecidedAt;ProductionWrite=$Decision.ProductionWrite;ChangesApplied=$Decision.ChangesApplied} }
function New-RapBlockedReplayDecision { param($Promotion,$Identity,[string]$Reason) [pscustomobject]@{PSTypeName='Rap.ZoteroDecision';DecisionId='';ProjectId=$Promotion.ProjectId;ResearchQuestionId=$Promotion.ResearchQuestionId;CandidateId=$Promotion.CandidateId;PromotionHash=$Promotion.PromotionHash;Decision='BLOCKED';Reason=$Reason;CanonicalKey=$Identity.CanonicalKey;ZoteroItemId=$null;State='BLOCKED';ProductionWrite='DISABLED';ChangesApplied=$false} }
function Test-RapDecisionAuditProof { param($Store,$Decision)
    $revalidation=@($Store.Audit|Where-Object{[long]$_.Sequence-eq[long]$Decision.RevalidationSequence});$decided=@($Store.Audit|Where-Object{[long]$_.Sequence-eq[long]$Decision.DecisionAuditSequence})
    if($revalidation.Count-ne1-or$decided.Count-ne1){return $false};$r=$revalidation[0];$d=$decided[0]
    $r.Event-ceq'PROMOTION_LINEAGE_REVALIDATED'-and$r.Data.DecisionId-ceq$Decision.DecisionId-and$r.Data.CandidateId-ceq$Decision.CandidateId-and$r.Data.PromotionHash-ceq$Decision.PromotionHash-and$r.Data.Result-ceq'PASS'-and$r.Data.EvidenceHash-ceq$Decision.RevalidationEvidenceHash-and$d.Event-ceq'PRE_ZOTERO_DEDUP_DECIDED'-and$d.Data.DecisionId-ceq$Decision.DecisionId-and$d.Data.DecisionBindingHash-ceq$Decision.DecisionBindingHash-and$d.Data.IdentityBindingHash-ceq$Decision.IdentityBindingHash-and[string]$d.Data.CanonicalTargetIdentity-ceq[string]$Decision.CanonicalTargetIdentity-and[string]$d.Data.ZoteroItemId-ceq[string]$Decision.ZoteroItemId-and[string]$d.Data.ZoteroLibraryContext-ceq[string]$Decision.ZoteroLibraryContext-and[string]$d.Data.ExactTargetEvidenceHash-ceq[string]$Decision.ExactTargetEvidenceHash-and[long]$r.Sequence-lt[long]$d.Sequence
}
function New-RapLookupSnapshot { param([string]$Outcome,[string]$Reason,[object[]]$Canonical,[object[]]$Zotero,[string]$ExecutionId)
    [pscustomobject]@{Status=$Outcome;Reason=$Reason;CanonicalStatus=$(if($Outcome-ceq'PASS'){'AUTHORITATIVE'}else{'UNKNOWN'});ZoteroStatus=$(if($Outcome-ceq'PASS'){'AUTHORITATIVE'}else{'UNKNOWN'});ExecutionId=$ExecutionId;ExecutedAt=[DateTimeOffset]::UtcNow.ToString('o');CanonicalCount=@($Canonical).Count;ZoteroCount=@($Zotero).Count;ReadOnly=$true;ProductionWrite='DISABLED'}
}

function New-RapResearchIntakeStore {
    [CmdletBinding()]param([Parameter(Mandatory)][string[]]$KnownProjectIds,[object[]]$ExistingCanonicalPapers=@(),[object[]]$ExistingZoteroItems=@(),[string]$DatabasePath='')
    foreach($project in $KnownProjectIds){Assert-RapProjectId $project}
    $canonical=@($ExistingCanonicalPapers|ForEach-Object{Copy-RapIntakeValue $_});$zotero=@($ExistingZoteroItems|ForEach-Object{Copy-RapIntakeValue $_})
    $s=[pscustomobject]@{PSTypeName='Rap.ResearchIntakeStore';SchemaVersion=4;DatabasePath=$(if($DatabasePath){[IO.Path]::GetFullPath($DatabasePath)}else{''});KnownProjectIds=@($KnownProjectIds|Sort-Object -Unique);Questions=@{};Searches=@{};Inbox=@{};Promotions=@{};IdentityResults=@{};LookupSnapshot=(New-RapLookupSnapshot 'LOOKUP_FAILED' 'LOOKUP_REQUIRED' @() @() 'LOOKUP-NOT-EXECUTED');LookupResults=@{};Decisions=@{};Lifecycles=@{};CanonicalPapers=$canonical;ZoteroItems=$zotero;Audit=[Collections.Generic.List[object]]::new();Counters=[pscustomobject]@{ZoteroCreateDecision=0;ZoteroMutation=0;DriveMutation=0;NotionMutation=0;LibraryIdAllocation=0;PaperReviewCreation=0};ProductionWrite='DISABLED';ProductionPilot='TEST_DEFERRED'};if($s.DatabasePath){[void](Save-RapResearchIntakeStore $s)};$s
}

function New-RapResearchQuestion {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][string]$ProjectId,[Parameter(Mandatory)][ValidatePattern('^RQ-[A-Za-z0-9._:-]{1,120}$')][string]$ResearchQuestionId,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Question,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Provenance)
    Assert-RapProjectId $ProjectId;if($ProjectId-cnotin$Store.KnownProjectIds){throw 'UNKNOWN_PROJECT_ID'}
    if($Store.Questions.ContainsKey($ResearchQuestionId)){throw 'DUPLICATE_RESEARCH_QUESTION_ID'}
    $record=[pscustomobject]@{PSTypeName='Rap.ResearchQuestion';ProjectId=$ProjectId;ResearchQuestionId=$ResearchQuestionId;Question=$Question.Trim();Provenance=$Provenance;CreatedAt=[DateTimeOffset]::UtcNow.ToString('o');State='DEFINED';ProductionWrite='DISABLED'}
    $Store.Questions[$ResearchQuestionId]=$record;[void](Add-RapIntakeAudit $Store 'RESEARCH_QUESTION_DEFINED' 'DEFINED' @{ProjectId=$ProjectId;ResearchQuestionId=$ResearchQuestionId;Provenance=$Provenance});Copy-RapIntakeValue $record
}

function New-RapSearchRequest {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][string]$ProjectId,[Parameter(Mandatory)][string]$ResearchQuestionId,[Parameter(Mandatory)][ValidateSet('QUICK','SYSTEMATIC')][string]$Mode,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Query,[hashtable]$Criteria=@{},[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Provenance,[Parameter(Mandatory)][ValidatePattern('^SE-[A-Za-z0-9._:-]{1,120}$')][string]$SearchExecutionId)
    Assert-RapProjectId $ProjectId;if(-not$Store.Questions.ContainsKey($ResearchQuestionId)){throw 'UNKNOWN_RESEARCH_QUESTION'};$question=$Store.Questions[$ResearchQuestionId];if($question.ProjectId-cne$ProjectId){throw 'PROJECT_ID_SUBSTITUTION'}
    if($Mode-ceq'SYSTEMATIC'-and$Criteria.Count-eq0){throw 'SYSTEMATIC_CRITERIA_REQUIRED'}
    if($Store.Searches.ContainsKey($SearchExecutionId)){throw 'DUPLICATE_SEARCH_EXECUTION_ID'}
    [pscustomobject]@{PSTypeName='Rap.SearchRequest';ProjectId=$ProjectId;ResearchQuestionId=$ResearchQuestionId;Mode=$Mode;Query=$Query.Trim();Criteria=[pscustomobject]$Criteria;Provenance=$Provenance;SearchExecutionId=$SearchExecutionId;RequestedAt=[DateTimeOffset]::UtcNow.ToString('o');ProductionWrite='DISABLED'}
}

function Invoke-RapMockResearchSearch {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)]$SearchRequest,[Parameter(Mandatory)][object[]]$FixtureResults)
    if($SearchRequest.PSObject.TypeNames-cnotcontains'Rap.SearchRequest'){throw 'UNTRUSTED_SEARCH_REQUEST'}
    if($SearchRequest.Mode-cne'QUICK'){throw 'SEARCH_MODE_NOT_IMPLEMENTED'}
    if($Store.Searches.ContainsKey($SearchRequest.SearchExecutionId)){throw 'DUPLICATE_SEARCH_EXECUTION_ID'}
    $seen=@{};$results=@();$rank=0
    foreach($fixture in $FixtureResults){$rank++;$candidateId=[string](Get-RapProperty $fixture 'CandidateId');if($candidateId-notmatch'^C-[A-Za-z0-9._:-]{1,120}$'){throw 'INVALID_CANDIDATE_ID'};if($seen.ContainsKey($candidateId)){throw 'DUPLICATE_CANDIDATE_ID'};$seen[$candidateId]=$true
        $results+=[pscustomobject]@{PSTypeName='Rap.SearchResult';ProjectId=$SearchRequest.ProjectId;ResearchQuestionId=$SearchRequest.ResearchQuestionId;SearchExecutionId=$SearchRequest.SearchExecutionId;SearchMode=$SearchRequest.Mode;CandidateId=$candidateId;Rank=$rank;Title=[string](Get-RapProperty $fixture 'Title');FirstAuthor=[string](Get-RapProperty $fixture 'FirstAuthor');Year=[string](Get-RapProperty $fixture 'Year');Doi=[string](Get-RapProperty $fixture 'Doi');Pmid=[string](Get-RapProperty $fixture 'Pmid');Pmcid=[string](Get-RapProperty $fixture 'Pmcid');PublisherId=[string](Get-RapProperty $fixture 'PublisherId');Source=[string](Get-RapProperty $fixture 'Source');RetrievedAt=[DateTimeOffset]::UtcNow.ToString('o');Provenance=[string](Get-RapProperty $fixture 'Provenance');State='SEARCHED';ProductionWrite='DISABLED'}
    }
    $Store.Searches[$SearchRequest.SearchExecutionId]=[pscustomobject]@{Request=Copy-RapIntakeValue $SearchRequest;Results=@($results|ForEach-Object{Copy-RapIntakeValue $_});State='SEARCHED'}
    [void](Add-RapIntakeAudit $Store 'SEARCH_EXECUTED' 'SEARCHED' @{ProjectId=$SearchRequest.ProjectId;ResearchQuestionId=$SearchRequest.ResearchQuestionId;SearchExecutionId=$SearchRequest.SearchExecutionId;Mode=$SearchRequest.Mode;CandidateCount=$results.Count})
    @($results)
}

function Add-RapResearchInboxCandidates {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][object[]]$SearchResults,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Reason)
    $added=@();foreach($result in $SearchResults){if($result.PSObject.TypeNames-cnotcontains'Rap.SearchResult'){throw 'ENTITY_BOUNDARY_VIOLATION'};if([string]::IsNullOrWhiteSpace([string]$result.Provenance)){throw 'MISSING_PROVENANCE'};if($Store.Inbox.ContainsKey($result.CandidateId)){throw 'DUPLICATE_CANDIDATE_ID'}
        $candidate=[pscustomobject]@{PSTypeName='Rap.ResearchInboxCandidate';ProjectId=$result.ProjectId;ResearchQuestionId=$result.ResearchQuestionId;SearchExecutionId=$result.SearchExecutionId;SearchMode=$result.SearchMode;CandidateId=$result.CandidateId;Title=$result.Title;FirstAuthor=$result.FirstAuthor;Year=$result.Year;Doi=$result.Doi;Pmid=$result.Pmid;Pmcid=$result.Pmcid;PublisherId=$result.PublisherId;Source=$result.Source;SearchRank=$result.Rank;InboxReason=$Reason;SearchProvenance=$result.Provenance;InboxedAt=[DateTimeOffset]::UtcNow.ToString('o');State='INBOXED';Stale=$false;ProductionWrite='DISABLED'}
        $Store.Inbox[$candidate.CandidateId]=$candidate;$Store.Lifecycles[$candidate.CandidateId]='INBOXED';$added+=Copy-RapIntakeValue $candidate;[void](Add-RapIntakeAudit $Store 'CANDIDATE_INBOXED' 'INBOXED' @{ProjectId=$candidate.ProjectId;ResearchQuestionId=$candidate.ResearchQuestionId;SearchExecutionId=$candidate.SearchExecutionId;CandidateId=$candidate.CandidateId;Reason=$Reason})
    };@($added)
}

function Promote-RapResearchInboxCandidate {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][string]$ProjectId,[Parameter(Mandatory)][string]$ResearchQuestionId,[Parameter(Mandatory)][string]$CandidateId,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Researcher,[Parameter(Mandatory)][ValidateNotNullOrEmpty()][string]$Provenance)
    Assert-RapProjectId $ProjectId;if(-not$Store.Inbox.ContainsKey($CandidateId)){throw 'UNKNOWN_INBOX_CANDIDATE'};$candidate=$Store.Inbox[$CandidateId]
    if($candidate.ProjectId-cne$ProjectId-or$candidate.ResearchQuestionId-cne$ResearchQuestionId){throw 'CANDIDATE_SUBSTITUTION'}
    if($candidate.Stale){throw 'STALE_CANDIDATE'};if([string]::IsNullOrWhiteSpace($Provenance)){throw 'MISSING_PROVENANCE'}
    if($Store.Promotions.ContainsKey($CandidateId)){$existing=$Store.Promotions[$CandidateId];if($existing.ProjectId-cne$ProjectId-or$existing.ResearchQuestionId-cne$ResearchQuestionId-or$existing.Researcher-cne$Researcher-or$existing.Provenance-cne$Provenance){throw 'PROMOTION_REPLAY_CONFLICT'};return $existing}
    if(@($Store.Promotions.Values|Where-Object{$_.ResearchQuestionId-ceq$ResearchQuestionId}).Count-ge1){throw 'PROMOTE_ONE_LIMIT_EXCEEDED'}
    $promotedAt=[DateTimeOffset]::UtcNow.ToString('o');$candidateHash=Get-RapIntakeHash (Get-RapCandidateIdentitySnapshot $candidate)
    $promotion=[pscustomobject]@{PSTypeName='Rap.ResearchPromotion';ProjectId=$ProjectId;ResearchQuestionId=$ResearchQuestionId;SearchExecutionId=$candidate.SearchExecutionId;SearchMode=$candidate.SearchMode;SearchSource=$candidate.Source;SearchProvenance=$candidate.SearchProvenance;CandidateId=$CandidateId;CandidateIdentityHash=$candidateHash;Researcher=$Researcher;Provenance=$Provenance;PromotedAt=$promotedAt;PromotionHash='';State='PROMOTED';ProductionWrite='DISABLED'}
    $promotion.PromotionHash=Get-RapIntakeHash (Get-RapPromotionBinding $promotion)
    $Store.Promotions[$CandidateId]=$promotion;$candidate.State='PROMOTED';$Store.Lifecycles[$CandidateId]='PROMOTED';[void](Add-RapIntakeAudit $Store 'CANDIDATE_PROMOTED' 'PROMOTED' @{ProjectId=$ProjectId;ResearchQuestionId=$ResearchQuestionId;CandidateId=$CandidateId;Researcher=$Researcher;PromotionHash=$promotion.PromotionHash;Provenance=$Provenance});$promotion
}

function Resolve-RapCanonicalPaperIdentity {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)]$Promotion)
    $persisted=Assert-RapPromotionBinding $Store $Promotion;if($Store.IdentityResults.ContainsKey($Promotion.CandidateId)){$trusted=Assert-RapIdentityAuthority $Store $Promotion $Store.IdentityResults[$Promotion.CandidateId];$copy=Copy-RapIntakeValue $trusted;$copy.PSObject.TypeNames.Insert(0,'Rap.IdentityResolution');return $copy};$candidate=$Store.Inbox[$Promotion.CandidateId];$Store.Lifecycles[$candidate.CandidateId]='IDENTITY_RESOLVING';if($Store.DatabasePath){[void](Save-RapResearchIntakeStore $Store)}
    try{$doi=Normalize-RapDoi $candidate.Doi}catch{return [pscustomobject]@{PSTypeName='Rap.IdentityResolution';CandidateId=$candidate.CandidateId;Status='INVALID';Authority='NONE';CanonicalKey=$null;NormalizedDoi=$null;Evidence=@('MALFORMED_DOI');State='BLOCKED';ProductionWrite='DISABLED'}}
    $pmid=Normalize-RapText $candidate.Pmid;$pmcid=Normalize-RapText $candidate.Pmcid;$publisher=Normalize-RapText $candidate.PublisherId;$signature=Get-RapMetadataSignature $candidate
    $authority=if($doi){'DOI'}elseif($pmid-or$pmcid){'STRONG_EXTERNAL_ID'}elseif($publisher){'PUBLISHER_SOURCE'}elseif($signature-notmatch'^\|\|$' -and $candidate.Title -and $candidate.FirstAuthor -and $candidate.Year){'TITLE_AUTHOR_YEAR'}else{'FUZZY_ONLY'}
    $key=switch($authority){'DOI'{"doi:$doi"};'STRONG_EXTERNAL_ID'{if($pmid){"pmid:$pmid"}else{"pmcid:$pmcid"}};'PUBLISHER_SOURCE'{"publisher:$publisher"};'TITLE_AUTHOR_YEAR'{"tay:$signature"};default{$null}}
    $status=if($authority-eq'FUZZY_ONLY'){'AMBIGUOUS'}else{'RESOLVED'};$state=if($status-eq'RESOLVED'){'IDENTITY_RESOLVED'}else{'AMBIGUOUS'}
    $resolution=[pscustomobject]@{PSTypeName='Rap.IdentityResolution';IdentityBindingVersion=1;IdentityId=('IDENTITY-'+[guid]::NewGuid().ToString('N'));ProjectId=$candidate.ProjectId;ResearchQuestionId=$candidate.ResearchQuestionId;SearchExecutionId=$candidate.SearchExecutionId;CandidateId=$candidate.CandidateId;PromotionHash=$persisted.PromotionHash;CandidateIdentityHash=$persisted.CandidateIdentityHash;ObservedDoi=$candidate.Doi;ObservedPmid=$candidate.Pmid;ObservedPmcid=$candidate.Pmcid;ObservedPublisherId=$candidate.PublisherId;Title=$candidate.Title;FirstAuthor=$candidate.FirstAuthor;Year=$candidate.Year;Status=$status;Authority=$authority;CanonicalKey=$key;NormalizedDoi=$doi;Pmid=$pmid;Pmcid=$pmcid;PublisherId=$publisher;MetadataSignature=$signature;Evidence=@($authority);ResolvedAt=[DateTimeOffset]::UtcNow.ToString('o');Provenance='candidate-derived:sealed';IdentityBindingHash='';State=$state;ProductionWrite='DISABLED'}
    $stored=Copy-RapIntakeValue $resolution;$stored.PSObject.TypeNames.Insert(0,'Rap.IdentityResolution');$bindingHash=Get-RapIntakeHash (Get-RapIdentityBinding $stored);$stored.IdentityBindingHash=$bindingHash;$resolution.IdentityBindingHash=$bindingHash;$Store.IdentityResults[$candidate.CandidateId]=$stored;$Store.Lifecycles[$candidate.CandidateId]=$state;[void](Add-RapIntakeAudit $Store 'IDENTITY_RESOLVED' $state @{IdentityId=$resolution.IdentityId;IdentityBindingHash=$bindingHash;PromotionHash=$resolution.PromotionHash;CandidateId=$candidate.CandidateId;Status=$status;Authority=$authority;CanonicalKey=$key;ObservedIdentifiers="doi=$doi;pmid=$pmid;pmcid=$pmcid;publisher=$publisher"});$copy=Copy-RapIntakeValue $stored;$copy.PSObject.TypeNames.Insert(0,'Rap.IdentityResolution');$copy
}

function Get-RapPreZoteroDedupDecision {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)]$Promotion,[Parameter(Mandatory)]$IdentityResolution)
    $persistedPromotion=Assert-RapPromotionBinding $Store $Promotion;if($Promotion.CandidateId-cne$IdentityResolution.CandidateId){throw 'CANDIDATE_SUBSTITUTION'}
    if($IdentityResolution.Status-cne'RESOLVED'){return [pscustomobject]@{PSTypeName='Rap.ZoteroDecision';CandidateId=$Promotion.CandidateId;Decision=$(if($IdentityResolution.Status-eq'INVALID'){'BLOCKED'}else{'AMBIGUOUS'});Reason=$IdentityResolution.Status;CanonicalKey=$null;ZoteroItemId=$null;State=$(if($IdentityResolution.Status-eq'INVALID'){'BLOCKED'}else{'AMBIGUOUS'});ProductionWrite='DISABLED';ChangesApplied=$false}}
    $IdentityResolution=Assert-RapIdentityAuthority $Store $Promotion $IdentityResolution
    $candidate=$Store.Inbox[$Promotion.CandidateId];$snapshot=$Store.LookupSnapshot;$canonicalMatches=@($Store.CanonicalPapers|Where-Object{[string]$_.CanonicalKey-ceq$IdentityResolution.CanonicalKey});$zoteroMatches=@($Store.ZoteroItems|Where-Object{[string]$_.CanonicalKey-ceq$IdentityResolution.CanonicalKey})
    $canonicalStatus=if($snapshot.Status-cne'PASS'){'UNKNOWN'}elseif($canonicalMatches.Count-eq0){'NOT_FOUND'}elseif($canonicalMatches.Count-eq1){'FOUND'}else{'MULTIPLE'};$zoteroStatus=if($snapshot.Status-cne'PASS'){'UNKNOWN'}elseif($zoteroMatches.Count-eq0){'NOT_FOUND'}elseif($zoteroMatches.Count-eq1){'FOUND'}else{'MULTIPLE'}
    $identityEvidenceHash=Get-RapIdentityEvidenceHash $IdentityResolution;$lookupEvidenceHash=Get-RapLookupEvidenceHash $Store $IdentityResolution
    $decisionId=if($Store.Decisions.ContainsKey($Promotion.CandidateId)){[string]$Store.Decisions[$Promotion.CandidateId].DecisionId}else{'DEC-'+[guid]::NewGuid().ToString('N')}
    $revalidationEvidenceHash=Get-RapIntakeHash ([ordered]@{DecisionId=$decisionId;ProjectId=$persistedPromotion.ProjectId;ResearchQuestionId=$persistedPromotion.ResearchQuestionId;SearchExecutionId=$persistedPromotion.SearchExecutionId;CandidateId=$persistedPromotion.CandidateId;PromotionHash=$persistedPromotion.PromotionHash;CandidateIdentityHash=$persistedPromotion.CandidateIdentityHash;IdentityEvidenceHash=$identityEvidenceHash;LookupExecutionId=$snapshot.ExecutionId;LookupEvidenceHash=$lookupEvidenceHash;Result='PASS'})
    $revalidation=Add-RapIntakeAudit $Store 'PROMOTION_LINEAGE_REVALIDATED' 'LINEAGE_REVALIDATED' @{DecisionId=$decisionId;ProjectId=$persistedPromotion.ProjectId;ResearchQuestionId=$persistedPromotion.ResearchQuestionId;SearchExecutionId=$persistedPromotion.SearchExecutionId;CandidateId=$persistedPromotion.CandidateId;PromotionHash=$persistedPromotion.PromotionHash;CurrentLineageHash=$persistedPromotion.PromotionHash;CandidateIdentityHash=$persistedPromotion.CandidateIdentityHash;IdentityEvidenceHash=$identityEvidenceHash;LookupExecutionId=$snapshot.ExecutionId;LookupEvidenceHash=$lookupEvidenceHash;Result='PASS';EvidenceHash=$revalidationEvidenceHash}
    if($Store.Decisions.ContainsKey($Promotion.CandidateId)){
        $existing=$Store.Decisions[$Promotion.CandidateId];$valid=$true
        foreach($name in @('BindingVersion','DecisionId','ProjectId','ResearchQuestionId','SearchExecutionId','CandidateId','PromotionHash','CandidateIdentityHash','IdentityBindingHash','IdentityEvidenceHash','CanonicalTargetIdentity','ZoteroLibraryContext','ExactTargetEvidenceHash','LookupExecutionId','LookupEvidenceHash','DecisionBindingHash','RevalidationSequence','RevalidationEvidenceHash','DecisionAuditSequence','DecidedAt')){if(-not$existing.PSObject.Properties[$name]){$valid=$false}}
        if($valid){$valid=(Get-RapIntakeHash (Get-RapDecisionBinding $existing))-ceq$existing.DecisionBindingHash-and$existing.ProjectId-ceq$Promotion.ProjectId-and$existing.ResearchQuestionId-ceq$Promotion.ResearchQuestionId-and$existing.SearchExecutionId-ceq$Promotion.SearchExecutionId-and$existing.CandidateId-ceq$Promotion.CandidateId-and$existing.PromotionHash-ceq$Promotion.PromotionHash-and$existing.CandidateIdentityHash-ceq$persistedPromotion.CandidateIdentityHash-and$existing.IdentityBindingHash-ceq$IdentityResolution.IdentityBindingHash-and$existing.IdentityEvidenceHash-ceq$identityEvidenceHash-and$existing.LookupExecutionId-ceq$snapshot.ExecutionId-and$existing.LookupEvidenceHash-ceq$lookupEvidenceHash-and(Test-RapDecisionAuditProof $Store $existing)}
        if($valid){return $existing};[void](Add-RapIntakeAudit $Store 'DECISION_REUSE_BLOCKED' 'BLOCKED' @{DecisionId=$decisionId;CandidateId=$Promotion.CandidateId;Reason='STALE_OR_INVALID_DECISION_EVIDENCE';CurrentLookupEvidenceHash=$lookupEvidenceHash});return New-RapBlockedReplayDecision $Promotion $IdentityResolution 'STALE_OR_INVALID_DECISION_EVIDENCE'
    }
    $Store.Lifecycles[$Promotion.CandidateId]='DEDUP_CHECKED';$Store.LookupResults[$Promotion.CandidateId]=[pscustomobject]@{PSTypeName='Rap.IntakeLookupResult';CandidateId=$Promotion.CandidateId;CanonicalKey=$IdentityResolution.CanonicalKey;CanonicalStatus=$canonicalStatus;ZoteroStatus=$zoteroStatus;CanonicalCount=$canonicalMatches.Count;ZoteroCount=$zoteroMatches.Count;LookupExecutionId=$snapshot.ExecutionId;LookupExecutedAt=$snapshot.ExecutedAt;LookupReason=$snapshot.Reason;ReadOnly=$true;ProductionWrite='DISABLED'};if($Store.DatabasePath){[void](Save-RapResearchIntakeStore $Store)}
    $allExisting=@($Store.CanonicalPapers)+@($Store.ZoteroItems);$conflicts=@($canonicalMatches+$zoteroMatches|Where-Object{Test-RapStrongMetadataConflict $candidate $_});$strongConflicts=@($allExisting|Where-Object{(($IdentityResolution.Pmid-and([string](Get-RapProperty $_ 'Pmid')-eq$IdentityResolution.Pmid))-or($IdentityResolution.Pmcid-and([string](Get-RapProperty $_ 'Pmcid')-eq$IdentityResolution.Pmcid)))-and([string]$_.CanonicalKey-cne$IdentityResolution.CanonicalKey)});$titleConflicts=@();if($IdentityResolution.Authority-eq'TITLE_AUTHOR_YEAR'){$title=Normalize-RapText $candidate.Title;$titleConflicts=@($allExisting|Where-Object{(Normalize-RapText ([string](Get-RapProperty $_ 'Title')))-eq$title-and[string]$_.CanonicalKey-cne$IdentityResolution.CanonicalKey})}
    if($snapshot.Status-cne'PASS'){$decisionName='BLOCKED';$reason="LOOKUP_NOT_AUTHORITATIVE:$($snapshot.Reason)";$zoteroId=$null}
    elseif($conflicts.Count-gt0-or$strongConflicts.Count-gt0-or$titleConflicts.Count-gt0){$decisionName='IDENTITY_CONFLICT';$reason='IDENTIFIER_METADATA_CONFLICT';$zoteroId=$null}
    elseif($canonicalMatches.Count-gt1-or$zoteroMatches.Count-gt1){$decisionName='AMBIGUOUS';$reason='MULTIPLE_EXISTING_MATCHES';$zoteroId=$null}
    elseif($canonicalMatches.Count-eq1-and$zoteroMatches.Count-eq0){$decisionName='BLOCKED';$reason='CANONICAL_EXISTS_ZOTERO_MAPPING_MISSING';$zoteroId=$null}
    elseif($canonicalMatches.Count-eq0-and$zoteroMatches.Count-eq1){$decisionName='BLOCKED';$reason='ZOTERO_EXISTS_CANONICAL_MAPPING_MISSING';$zoteroId=$null}
    elseif($zoteroMatches.Count-eq1){$decisionName='REUSE_EXISTING';$reason='CANONICAL_AND_ZOTERO_MATCH';$zoteroId=[string]$zoteroMatches[0].ZoteroItemId}
    elseif($canonicalStatus-ceq'NOT_FOUND'-and$zoteroStatus-ceq'NOT_FOUND'){$decisionName='CREATE_CANDIDATE';$reason='AUTHORITATIVE_NOT_FOUND';$zoteroId=$null}
    else{$decisionName='BLOCKED';$reason='LOOKUP_STATE_NOT_CREATE_AUTHORITY';$zoteroId=$null}
    $canonicalTarget='';$libraryContext='';$targetHash='';if($decisionName-ceq'REUSE_EXISTING'){$canonicalTarget=$IdentityResolution.CanonicalKey;$libraryContext=[string](Get-RapProperty $zoteroMatches[0] 'LibraryId');if([string]::IsNullOrWhiteSpace($libraryContext)){$libraryContext=[string](Get-RapProperty $zoteroMatches[0] 'LibraryContext')};if([string]::IsNullOrWhiteSpace($libraryContext)){$libraryContext='LOCAL_FIXTURE'};$targetHash=Get-RapIntakeHash ([ordered]@{CanonicalTargetIdentity=$canonicalTarget;ZoteroItemId=$zoteroId;ZoteroLibraryContext=$libraryContext;CanonicalMatch=$canonicalMatches[0];ZoteroMatch=$zoteroMatches[0]})}
    $decision=[pscustomobject]@{PSTypeName='Rap.ZoteroDecision';BindingVersion=2;DecisionId=$decisionId;ProjectId=$Promotion.ProjectId;ResearchQuestionId=$Promotion.ResearchQuestionId;SearchExecutionId=$Promotion.SearchExecutionId;CandidateId=$Promotion.CandidateId;PromotionHash=$Promotion.PromotionHash;CandidateIdentityHash=$persistedPromotion.CandidateIdentityHash;IdentityBindingHash=$IdentityResolution.IdentityBindingHash;IdentityEvidenceHash=$identityEvidenceHash;Decision=$decisionName;Reason=$reason;CanonicalKey=$IdentityResolution.CanonicalKey;CanonicalTargetIdentity=$canonicalTarget;CanonicalStatus=$canonicalStatus;ZoteroStatus=$zoteroStatus;LookupExecutionId=$snapshot.ExecutionId;LookupExecutedAt=$snapshot.ExecutedAt;LookupEvidenceHash=$lookupEvidenceHash;CanonicalMatches=$canonicalMatches.Count;ZoteroMatches=$zoteroMatches.Count;ZoteroItemId=$zoteroId;ZoteroLibraryContext=$libraryContext;ExactTargetEvidenceHash=$targetHash;State=$decisionName;RevalidationSequence=$revalidation.Sequence;RevalidationEvidenceHash=$revalidationEvidenceHash;DecidedAt=[DateTimeOffset]::UtcNow.ToString('o');DecisionBindingHash='';DecisionAuditSequence=0;ProductionWrite='DISABLED';ChangesApplied=$false}
    $decision.DecisionBindingHash=Get-RapIntakeHash (Get-RapDecisionBinding $decision)
    $decisionAudit=Add-RapIntakeAudit $Store 'PRE_ZOTERO_DEDUP_DECIDED' $decision.State @{DecisionId=$decision.DecisionId;DecisionBindingHash=$decision.DecisionBindingHash;CandidateId=$Promotion.CandidateId;PromotionHash=$Promotion.PromotionHash;IdentityBindingHash=$decision.IdentityBindingHash;RevalidationSequence=$decision.RevalidationSequence;RevalidationEvidenceHash=$decision.RevalidationEvidenceHash;CanonicalKey=$decision.CanonicalKey;CanonicalTargetIdentity=$decision.CanonicalTargetIdentity;ZoteroItemId=$decision.ZoteroItemId;ZoteroLibraryContext=$decision.ZoteroLibraryContext;ExactTargetEvidenceHash=$decision.ExactTargetEvidenceHash;CanonicalStatus=$decision.CanonicalStatus;ZoteroStatus=$decision.ZoteroStatus;LookupExecutionId=$decision.LookupExecutionId;LookupEvidenceHash=$decision.LookupEvidenceHash;Decision=$decision.Decision;Reason=$decision.Reason}
    $decision.DecisionAuditSequence=$decisionAudit.Sequence;if($decisionName-ceq'CREATE_CANDIDATE'){$Store.Counters.ZoteroCreateDecision++};$Store.Decisions[$Promotion.CandidateId]=$decision;$Store.Lifecycles[$Promotion.CandidateId]=$decision.State;if($Store.DatabasePath){[void](Save-RapResearchIntakeStore $Store)};$decision
}

function Invoke-RapResearchIntakeDecision {
    [CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)]$Promotion)
    if($Store.ProductionWrite-cne'DISABLED'-or$Store.ProductionPilot-cne'TEST_DEFERRED'){throw 'UNSAFE_RESEARCH_INTAKE_MODE'}
    $identity=Resolve-RapCanonicalPaperIdentity $Store $Promotion;$decision=Get-RapPreZoteroDedupDecision $Store $Promotion $identity
    [pscustomobject]@{Identity=$identity;Decision=$decision;ProductionWrite='DISABLED';ProductionPilot='TEST_DEFERRED';ProductionMutations=[pscustomobject]@{Zotero=$Store.Counters.ZoteroMutation;Drive=$Store.Counters.DriveMutation;Notion=$Store.Counters.NotionMutation};LibraryIdAllocations=$Store.Counters.LibraryIdAllocation;PaperReviewsCreated=$Store.Counters.PaperReviewCreation}
}
function Get-RapResearchIntakeAudit { [CmdletBinding()]param([Parameter(Mandatory)]$Store) @($Store.Audit|ForEach-Object{Copy-RapIntakeValue $_}) }
function Get-RapResearchIntakeRecoveryStatus {[CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][string]$CandidateId)if(-not$Store.Lifecycles.ContainsKey($CandidateId)){throw 'UNKNOWN_INBOX_CANDIDATE'};$s=[string]$Store.Lifecycles[$CandidateId];[pscustomobject]@{CandidateId=$CandidateId;PersistedState=$s;Status=$(if($s-in@('IDENTITY_RESOLVING','DEDUP_CHECKED')){'RECOVERY_REQUIRED'}elseif($s-in@('CREATE_CANDIDATE','REUSE_EXISTING','AMBIGUOUS','IDENTITY_CONFLICT','BLOCKED')){'ALREADY_COMPLETED'}else{'RESUMABLE'});AutomaticAdvance=$false;ProductionWrite='DISABLED'} }
function Invoke-RapResearchIntakeReadOnlyLookup {[CmdletBinding()]param([Parameter(Mandatory)]$Store,[Parameter(Mandatory)][ValidateSet('PASS','TIMEOUT','NETWORK_FAILURE','MALFORMED','AUTH_FAILURE','PERMISSION_AMBIGUITY','PARTIAL','UNKNOWN','MULTIPLE')][string]$Outcome,[object[]]$CanonicalResults=@(),[object[]]$ZoteroResults=@())
    if($Store.ProductionWrite-cne'DISABLED'){throw 'UNSAFE_RESEARCH_INTAKE_MODE'};$executionId='LOOKUP-'+[guid]::NewGuid().ToString('N')
    $reason=$Outcome;if($Outcome-ceq'PASS'){foreach($x in @($CanonicalResults+$ZoteroResults)){if(-not$x.PSObject.Properties['CanonicalKey']-or[string]::IsNullOrWhiteSpace([string]$x.CanonicalKey)){$Outcome='MALFORMED';$reason='MALFORMED';break}}}
    if($Outcome-ceq'PASS'){$Store.CanonicalPapers=@($CanonicalResults|ForEach-Object{Copy-RapIntakeValue $_});$Store.ZoteroItems=@($ZoteroResults|ForEach-Object{Copy-RapIntakeValue $_});$Store.LookupSnapshot=New-RapLookupSnapshot 'PASS' 'READ_ONLY_FIXTURE' $CanonicalResults $ZoteroResults $executionId}
    else{$Store.LookupSnapshot=New-RapLookupSnapshot 'LOOKUP_FAILED' $reason @() @() $executionId}
    [void](Add-RapIntakeAudit $Store 'READ_ONLY_LOOKUP_EXECUTED' $(if($Outcome-ceq'PASS'){'LOOKUP_COMPLETE'}else{'LOOKUP_FAILED'}) @{ExecutionId=$executionId;Outcome=$Outcome;Reason=$Store.LookupSnapshot.Reason;CanonicalStatus=$Store.LookupSnapshot.CanonicalStatus;ZoteroStatus=$Store.LookupSnapshot.ZoteroStatus;CanonicalCount=$Store.LookupSnapshot.CanonicalCount;ZoteroCount=$Store.LookupSnapshot.ZoteroCount})
    [pscustomobject]@{Status=$Store.LookupSnapshot.Status;Reason=$Store.LookupSnapshot.Reason;CanonicalStatus=$(if($Outcome-ceq'PASS'){if($CanonicalResults.Count-eq0){'NOT_FOUND'}elseif($CanonicalResults.Count-eq1){'FOUND'}else{'MULTIPLE'}}else{'UNKNOWN'});ZoteroStatus=$(if($Outcome-ceq'PASS'){if($ZoteroResults.Count-eq0){'NOT_FOUND'}elseif($ZoteroResults.Count-eq1){'FOUND'}else{'MULTIPLE'}}else{'UNKNOWN'});ExecutionId=$executionId;ChangesApplied=$false;ProductionWrite='DISABLED'}
}

Export-ModuleMember -Function New-RapResearchIntakeStore,New-RapResearchQuestion,New-RapSearchRequest,Invoke-RapMockResearchSearch,Add-RapResearchInboxCandidates,Promote-RapResearchInboxCandidate,Resolve-RapCanonicalPaperIdentity,Get-RapPreZoteroDedupDecision,Invoke-RapResearchIntakeDecision,Get-RapResearchIntakeAudit,Initialize-RapResearchIntakeStore,Save-RapResearchIntakeStore,Open-RapResearchIntakeStore,Test-RapResearchIntakeStoreIntegrity,Get-RapResearchIntakeRecoveryStatus,Invoke-RapResearchIntakeReadOnlyLookup
