Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot '../ResearchAutomation.Local/modules/Queue.psm1') -Force
function ConvertTo-RapRecText {param($Value)[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($Value|ConvertTo-Json -Depth 60 -Compress)))}
function ConvertFrom-RapRecText {param([string]$Value)if(!$Value){return $null};[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Value))|ConvertFrom-Json -Depth 60}
function ConvertTo-RapRecSql {param([string]$Value)"'"+$Value.Replace("'","''")+"'"}
function Initialize-RapReconciliationStore { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath)$p=Initialize-RapQueue $DatabasePath 5000;[Rap.NativeSqlite]::Execute($p,'CREATE TABLE IF NOT EXISTS ReconciliationSnapshots(ScopeKey TEXT PRIMARY KEY,Payload TEXT NOT NULL);CREATE TABLE IF NOT EXISTS ReconciliationAudit(Id INTEGER PRIMARY KEY AUTOINCREMENT,OperationId TEXT NOT NULL,Payload TEXT NOT NULL);',5000);$p }
function New-RapReconciliationSqliteDependencies {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath,[ValidateSet('None','AFTER_STATE','BEFORE_COMMIT')][string]$FaultPoint='None')
 $p=Initialize-RapReconciliationStore $DatabasePath;$enc=${function:ConvertTo-RapRecText};$dec=${function:ConvertFrom-RapRecText};$lit=${function:ConvertTo-RapRecSql}
 $read={param($libraryId,$projectId)$v=[Rap.NativeSqlite]::Scalar($p,"SELECT Payload FROM ReconciliationSnapshots WHERE ScopeKey=$(&$lit "$libraryId|$projectId");",5000);&$dec $v}.GetNewClosure()
 $get={param($id)$v=[Rap.NativeSqlite]::Scalar($p,"SELECT Payload FROM Operations WHERE OperationKey=$(&$lit ([string]$id)) AND Type='Reconciliation';",5000);&$dec $v}.GetNewClosure()
 $commit={param($snapshot,$operation,$audit)$scope="$($snapshot.LibraryId)|$($snapshot.ProjectId)";$s=&$enc $snapshot;$o=&$enc $operation;$a=&$enc $audit;$now=[DateTimeOffset]::UtcNow.ToString('o');$fault1=if($FaultPoint-eq'AFTER_STATE'){'INSERT INTO RapRecFault_AFTER_STATE(Value) VALUES(1);'}else{''};$fault2=if($FaultPoint-eq'BEFORE_COMMIT'){'INSERT INTO RapRecFault_BEFORE_COMMIT(Value) VALUES(1);'}else{''};$sql="BEGIN IMMEDIATE;INSERT OR REPLACE INTO ReconciliationSnapshots(ScopeKey,Payload) VALUES($(&$lit $scope),'$s');$fault1 INSERT INTO ReconciliationAudit(OperationId,Payload) VALUES($(&$lit ([string]$operation.OperationId)),'$a');INSERT OR REPLACE INTO Operations(OperationKey,Type,Payload,Status,CreatedUtc,UpdatedUtc) VALUES($(&$lit ([string]$operation.OperationId)),'Reconciliation','$o','COMPLETED','$now','$now');$fault2 COMMIT;";try{[Rap.NativeSqlite]::Execute($p,$sql,5000)}catch{if($FaultPoint-ne'None'){throw "INJECTED_FAULT:$FaultPoint transaction rolled back"};throw}}.GetNewClosure()
 [pscustomobject]@{ReadSnapshot=$read;GetOperation=$get;CommitRecovery=$commit;DatabasePath=$p;FaultPoint=$FaultPoint}
}
function Register-RapReconciliationFixture { [CmdletBinding()]param([Parameter(Mandatory)]$Snapshot,[Parameter(Mandatory)]$Dependencies)$scope="$($Snapshot.LibraryId)|$($Snapshot.ProjectId)";$s=ConvertTo-RapRecText $Snapshot;[Rap.NativeSqlite]::Execute($Dependencies.DatabasePath,"INSERT OR REPLACE INTO ReconciliationSnapshots(ScopeKey,Payload) VALUES($(ConvertTo-RapRecSql $scope),'$s');",5000) }
function Get-RapReconciliationSnapshot { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath,[Parameter(Mandatory)][string]$LibraryId,[Parameter(Mandatory)][string]$ProjectId)$d=New-RapReconciliationSqliteDependencies $DatabasePath;&$d.ReadSnapshot $LibraryId $ProjectId }
function Get-RapReconciliationAudit { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath)$p=Initialize-RapReconciliationStore $DatabasePath;$v=[Rap.NativeSqlite]::Scalar($p,"SELECT group_concat(Payload,',') FROM (SELECT Payload FROM ReconciliationAudit ORDER BY Id);",5000);if(!$v){return @()};@($v.Split(',')|ForEach-Object{ConvertFrom-RapRecText $_}) }
Export-ModuleMember -Function Initialize-RapReconciliationStore,New-RapReconciliationSqliteDependencies,Register-RapReconciliationFixture,Get-RapReconciliationSnapshot,Get-RapReconciliationAudit
