. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$script:N=0
function A([string]$id,[bool]$ok,[string]$message){$script:N++;if(!$ok){throw "$id failed: $message"};Write-Host "$id PASS $message"}
$s=New-RapResearchIntakeStore -KnownProjectIds PR015;$null=New-RapResearchQuestion $s PR015 RQ-A q p;$q=New-RapSearchRequest $s PR015 RQ-A QUICK q @{} p SE-A
A AD01 ((Get-RapIntakeThrown {Invoke-RapMockResearchSearch $s $q @((New-RapIntakeFixture C-D),(New-RapIntakeFixture C-D))})-match'DUPLICATE_CANDIDATE_ID') 'duplicate Candidate_ID blocked'
$c=New-RapIntakeContext -Results @((New-RapIntakeFixture C-M 'not-a-doi'));$p=Promote-RapFixture $c C-M;$r=Invoke-RapResearchIntakeDecision $c.Store $p;A AD02 ($r.Identity.Status-eq'INVALID'-and$r.Decision.Decision-eq'BLOCKED') 'malformed DOI blocks canonicalization'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].Doi='10.9999/substituted';A AD03 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'DOI substitution blocked'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$fake=[pscustomobject]@{PSTypeName='Rap.ResearchPromotion';CandidateId='C-OTHER';PromotionHash=$p.PromotionHash};A AD04 ((Get-RapIntakeThrown {Resolve-RapCanonicalPaperIdentity $c.Store $fake})-match'UNTRUSTED_PROMOTION') 'candidate substitution token blocked'
$c=New-RapIntakeContext;$c.Store.Inbox['C-001'].Stale=$true;A AD05 ((Get-RapIntakeThrown {Promote-RapFixture $c})-match'STALE_CANDIDATE') 'stale candidate blocked'
$bad=New-RapIntakeFixture;$bad.Provenance='';$s=New-RapResearchIntakeStore PR015;$null=New-RapResearchQuestion $s PR015 RQ-P q p;$q=New-RapSearchRequest $s PR015 RQ-P QUICK q @{} p SE-P;$x=@(Invoke-RapMockResearchSearch $s $q @($bad));A AD06 ((Get-RapIntakeThrown {Add-RapResearchInboxCandidates $s $x reason})-match'MISSING_PROVENANCE') 'missing provenance blocked'
$c=New-RapIntakeContext;A AD07 ((Get-RapIntakeThrown {Promote-RapResearchInboxCandidate $c.Store PR015 RQ-015 C-UNKNOWN r p})-match'UNKNOWN_INBOX_CANDIDATE') 'invalid state transition blocked'
$e=[pscustomobject]@{CanonicalKey='doi:10.1234/rap.001';Title='Research Intake Safety';FirstAuthor='Kim';Year='2026'};$c=New-RapIntakeContext @($e) @();$p=Promote-RapFixture $c;$r=Invoke-RapResearchIntakeDecision $c.Store $p;A AD08 ($r.Decision.Decision-eq'BLOCKED'-and$r.Decision.Reason-eq'CANONICAL_EXISTS_ZOTERO_MAPPING_MISSING') 'canonical paper with missing Zotero mapping blocks'
$e=[pscustomobject]@{CanonicalKey='doi:10.1234/rap.001';ZoteroItemId='Z-ORPHAN';Title='Research Intake Safety';FirstAuthor='Kim';Year='2026'};$c=New-RapIntakeContext @() @($e);$p=Promote-RapFixture $c;$r=Invoke-RapResearchIntakeDecision $c.Store $p;A AD09 ($r.Decision.Decision-eq'BLOCKED'-and$r.Decision.Reason-eq'ZOTERO_EXISTS_CANONICAL_MAPPING_MISSING') 'Zotero item with incomplete canonical mapping blocks'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$r1=Invoke-RapResearchIntakeDecision $c.Store $p;$r2=Invoke-RapResearchIntakeDecision $c.Store $p;A AD10 ($c.Store.Decisions.Count-eq1-and$c.Store.Counters.ZoteroCreateDecision-eq1-and$r2.ProductionMutations.Zotero-eq0) 'retry path is idempotent and mutation-free'
A AD11 (@(Get-Command -Module ResearchAutomation.ResearchIntake|Where-Object{$_.Name-match'Write|CreateZotero|Invoke-RestMethod|Callback'}).Count-eq0) 'no callback, connector, or direct-write API exported'
A AD12 ($c.Store.Counters.ZoteroMutation-eq0-and$c.Store.Counters.DriveMutation-eq0-and$c.Store.Counters.NotionMutation-eq0-and$r1.ProductionWrite-eq'DISABLED') 'all production mutations remain zero'
$c=New-RapIntakeContext;$null=Promote-RapFixture $c;A AD13 ((Get-RapIntakeThrown {Promote-RapResearchInboxCandidate $c.Store PR015 RQ-015 C-001 'other-researcher' 'changed-provenance'})-match'PROMOTION_REPLAY_CONFLICT') 'changed duplicate PROMOTE binding conflicts'
if($script:N-ne13){throw "Expected 13 adversarial assertions, got $script:N"};Write-Host 'SPR-015 Research Intake adversarial: AD01-AD13 13/13 PASS; production mutations: 0/0/0'
