$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$script:Pass=0;$script:Fail=0
function Gate-E([string]$id,[bool]$ok,[string]$detail){if($ok){$script:Pass++;Write-Host "$id PASS $detail"}else{$script:Fail++;Write-Host "$id FAIL $detail"}}
function No-Create([string]$outcome){$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeReadOnlyLookup $c.Store $outcome;$r=Invoke-RapResearchIntakeDecision $c.Store $p;$r.Decision.Decision-cne'CREATE_CANDIDATE'-and$c.Store.Counters.ZoteroCreateDecision-eq0}
function Existing([string]$id='Z1'){[pscustomobject]@{CanonicalKey='doi:10.1234/rap.001';ZoteroItemId=$id;Title='Research Intake Safety';FirstAuthor='Kim';Year='2026'}}

$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) '' $true;$p=Promote-RapFixture $c;$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E01 ($r.Decision.Decision-cne'CREATE_CANDIDATE') 'LOOKUP_REQUIRED cannot create'
Gate-E E02 (No-Create TIMEOUT) 'TIMEOUT cannot create'
Gate-E E03 (No-Create PARTIAL) 'PARTIAL cannot create'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.PSObject.Properties.Remove('LookupSnapshot');Gate-E E04 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-ne'') 'missing lookup evidence fails closed'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$e=Existing;$null=Invoke-RapResearchIntakeReadOnlyLookup $c.Store PASS @($e) @();$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E05 ($r.Decision.Decision-ceq'BLOCKED') 'canonical NOT_FOUND to FOUND invalidates CREATE'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$e=Existing;$null=Invoke-RapResearchIntakeReadOnlyLookup $c.Store PASS @() @($e);$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E06 ($r.Decision.Decision-ceq'BLOCKED') 'Zotero NOT_FOUND to FOUND invalidates CREATE'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$null=Invoke-RapResearchIntakeReadOnlyLookup $c.Store TIMEOUT;$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E07 ($r.Decision.Decision-ceq'BLOCKED') 'NOT_FOUND to TIMEOUT invalidates CREATE'

$temp=Join-Path ([IO.Path]::GetTempPath()) ('ri-turn-e-'+[guid]::NewGuid().ToString('N'));New-Item $temp -ItemType Directory|Out-Null
try{
    $db=Join-Path $temp 'launder.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].Reason='FORGED';Save-RapResearchIntakeStore $c.Store|Out-Null;$s=Open-RapResearchIntakeStore $db;$r=Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001'];Gate-E E08 ($r.Decision.Decision-ceq'BLOCKED') 'fresh envelope cannot launder stale decision'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].CandidateId='C-B';$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E09 ($r.Decision.Decision-ceq'BLOCKED') 'Candidate A decision cannot become Candidate B authority'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].ProjectId='PR999';$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E10 ($r.Decision.Decision-ceq'BLOCKED') 'Project A decision cannot become Project B authority'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].SearchExecutionId='SE-EVIL';Gate-E E11 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'SearchExecutionId substitution blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].CandidateId='C-EVIL';Gate-E E12 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'Candidate_ID substitution blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].Doi='10.9999/evil';Gate-E E13 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'DOI substitution blocked'
    $db=Join-Path $temp 'restart-lookup.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$s=Open-RapResearchIntakeStore $db;$e=Existing;$null=Invoke-RapResearchIntakeReadOnlyLookup $s PASS @($e) @($e);$r=Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001'];Gate-E E14 ($r.Decision.Decision-ceq'BLOCKED') 'restart plus changed lookup blocks old decision'
    $db=Join-Path $temp 'restart-lineage.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$s=Open-RapResearchIntakeStore $db;$s.Inbox['C-001'].SearchExecutionId='SE-EVIL';Save-RapResearchIntakeStore $s|Out-Null;$s=Open-RapResearchIntakeStore $db;Gate-E E15 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']})-match'CANDIDATE_SUBSTITUTION') 'restart plus changed lineage blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$c.Store.Audit.RemoveAt([int]$d.RevalidationSequence-1);$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E16 ($r.Decision.Decision-ceq'BLOCKED') 'missing revalidation audit blocks replay'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$d.RevalidationSequence=[long]$d.DecisionAuditSequence+1;$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E17 ($r.Decision.Decision-ceq'BLOCKED') 'revalidation after decision blocks replay'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$evt=@($c.Store.Audit|Where-Object{$_.Sequence-eq$d.RevalidationSequence})[0];$evt.Data.CandidateId='C-EVIL';$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-E E18 ($r.Decision.Decision-ceq'BLOCKED') 'wrong Candidate revalidation blocks replay'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Audit=$null;$thrown=Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p};Gate-E E19 (($thrown-ne'')-and$c.Store.Decisions.Count-eq0-and$c.Store.Counters.ZoteroCreateDecision-eq0) 'audit persistence failure cannot create decision'
    $db=Join-Path $temp 'legacy-v2.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;[Rap.NativeSqlite]::Execute($db,"UPDATE ResearchIntakeStore SET SchemaVersion=2 WHERE StoreId='PRIMARY';",5000);Gate-E E20 ((Get-RapIntakeThrown {Open-RapResearchIntakeStore $db})-match'SCHEMA_UNSUPPORTED') 'legacy schema cannot escalate to v4 authority'

    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$identity=Resolve-RapCanonicalPaperIdentity $c.Store $p;$identity.CanonicalKey='doi:10.9999/forged';$thrown=Get-RapIntakeThrown {Get-RapPreZoteroDedupDecision $c.Store $p $identity};Gate-E E21 ($thrown-match'IDENTITY_BINDING_MISMATCH') 'forged identity resolution cannot grant CREATE authority'
    $db=Join-Path $temp 'zotero-target.db';$e=Existing 'Z-GOOD';$c=New-RapIntakeContext @($e) @($e) @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].ZoteroItemId='Z-EVIL';Save-RapResearchIntakeStore $c.Store|Out-Null;$s=Open-RapResearchIntakeStore $db;$r=Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001'];Gate-E E22 ($r.Decision.ZoteroItemId-cne'Z-EVIL') 'DecisionBindingHash protects the selected Zotero target identity'
}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}

Write-Host "SPR-015 Turn E independent probes: PASS=$script:Pass FAIL=$script:Fail TOTAL=$($script:Pass+$script:Fail)"
if($script:Fail-gt0){Write-Host 'TURN_E_FINAL_GATE_PROBES=FAIL';exit 1}
Write-Host 'TURN_E_FINAL_GATE_PROBES=PASS'
