. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$pass=0;$fail=0
function G($id,$ok,$message){if($ok){$script:pass++;Write-Host "$id PASS $message"}else{$script:fail++;Write-Host "$id FAIL $message"}}
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].CandidateId='C-X';G GC01 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'candidate substitution'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;G GC02 ((Get-RapIntakeThrown {Promote-RapResearchInboxCandidate $c.Store PR999 RQ-015 C-001 r p})-match'CANDIDATE_SUBSTITUTION') 'project substitution'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].Doi='10.9999/x';G GC03 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p})-match'CANDIDATE_SUBSTITUTION') 'DOI substitution'
$e=[pscustomobject]@{CanonicalKey='doi:10.9999/other';ZoteroItemId='Z';Title='Research Intake Safety';FirstAuthor='Kim';Year='2026';Pmid='123'};$c=New-RapIntakeContext @($e) @($e) @((New-RapIntakeFixture C-004 '10.1234/rap.001' 'Research Intake Safety' 'Kim' '2026' '123'));$p=Promote-RapFixture $c C-004;$r=Invoke-RapResearchIntakeDecision $c.Store $p;G GC04 ($r.Decision.Decision-eq'IDENTITY_CONFLICT') 'DOI PMID conflict'
$tmp=Join-Path ([IO.Path]::GetTempPath()) ('rap-gc-'+[guid]::NewGuid());New-Item $tmp -ItemType Directory|Out-Null
try{$db=Join-Path $tmp 'x.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;[Rap.NativeSqlite]::Execute($db,"UPDATE ResearchIntakeStore SET RecordHash='x' WHERE StoreId='PRIMARY';",5000);G GC05 (-not(Test-RapResearchIntakeStoreIntegrity $db)) 'hash tampering';$db2=Join-Path $tmp 's.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db2;[Rap.NativeSqlite]::Execute($db2,"UPDATE ResearchIntakeStore SET SchemaVersion=99 WHERE StoreId='PRIMARY';",5000);G GC06 ((Get-RapIntakeThrown {Open-RapResearchIntakeStore $db2})-match'SCHEMA_UNSUPPORTED') 'unsupported schema'}finally{Remove-Item $tmp -Recurse -Force}
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Lifecycles['C-001']='IDENTITY_RESOLVING';G GC07 ((Get-RapResearchIntakeRecoveryStatus $c.Store C-001).Status-eq'RECOVERY_REQUIRED') 'identity resolving recovery'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Lifecycles['C-001']='DEDUP_CHECKED';G GC08 ((Get-RapResearchIntakeRecoveryStatus $c.Store C-001).Status-eq'RECOVERY_REQUIRED') 'dedup checked recovery'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$l=Invoke-RapResearchIntakeReadOnlyLookup $c.Store TIMEOUT;$r=Invoke-RapResearchIntakeDecision $c.Store $p;G GC09 ($r.Decision.Decision-ne'CREATE_CANDIDATE') 'timeout cannot be bypassed into CREATE'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$l=Invoke-RapResearchIntakeReadOnlyLookup $c.Store PARTIAL;$r=Invoke-RapResearchIntakeDecision $c.Store $p;G GC10 ($r.Decision.Decision-ne'CREATE_CANDIDATE') 'partial lookup cannot be bypassed into CREATE'
$c=New-RapIntakeContext;$p1=Promote-RapFixture $c;$r1=Invoke-RapResearchIntakeDecision $c.Store $p1;$p2=Promote-RapFixture $c;$r2=Invoke-RapResearchIntakeDecision $c.Store $p2;G GC11 ($c.Store.Decisions.Count-eq1-and$r1.Decision.Decision-eq$r2.Decision.Decision) 'duplicate promote replay'
$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture C-F '' 'Research Intake' '' ''));$p=Promote-RapFixture $c C-F;$r=Invoke-RapResearchIntakeDecision $c.Store $p;G GC12 ($r.Decision.Decision-eq'AMBIGUOUS') 'fuzzy-only no reuse'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Inbox['C-001'].SearchExecutionId='SE-SUBSTITUTED';$result=Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p};G GC13 ($result-match'CANDIDATE_SUBSTITUTION') 'search lineage substitution'
Write-Host "SPR-015 Turn C independent probes: PASS=$pass FAIL=$fail TOTAL=$($pass+$fail)"
if($fail-gt0){Write-Host 'TURN_C_GATE_PROBES=FAIL';exit 1}else{Write-Host 'TURN_C_GATE_PROBES=PASS'}
