$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$script:Pass=0;$script:Fail=0
function Gate-F([string]$id,[bool]$ok,[string]$detail){if($ok){$script:Pass++;Write-Host "$id PASS $detail"}else{$script:Fail++;Write-Host "$id FAIL $detail"}}
function Existing-F([string]$id='Z-GOOD',[string]$library='LIBRARY-1'){[pscustomobject]@{CanonicalKey='doi:10.1234/rap.001';ZoteroItemId=$id;LibraryId=$library;Title='Research Intake Safety';FirstAuthor='Kim';Year='2026'}}
function Identity-Attack-F([scriptblock]$change){$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$i=Resolve-RapCanonicalPaperIdentity $c.Store $p;&$change $i;(Get-RapIntakeThrown {Get-RapPreZoteroDedupDecision $c.Store $p $i})-match'(IDENTITY_BINDING_MISMATCH|CANDIDATE_SUBSTITUTION)'}
function Lookup-Attack-F([string]$outcome){$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeReadOnlyLookup $c.Store $outcome;$r=Invoke-RapResearchIntakeDecision $c.Store $p;$r.Decision.Decision-cne'CREATE_CANDIDATE'-and$c.Store.Counters.ZoteroCreateDecision-eq0}
function Reuse-Attack-F([scriptblock]$change){$e=Existing-F;$c=New-RapIntakeContext @($e) @($e);$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;&$change $c.Store.Decisions['C-001'];(Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED'}

Gate-F F01 (Identity-Attack-F {$args[0].CanonicalKey='doi:10.9999/other'}) 'identity substitution blocked'
Gate-F F02 (Identity-Attack-F {$args[0].NormalizedDoi='10.9999/other'}) 'DOI substitution blocked'
$c=New-RapIntakeContext -Results @((New-RapIntakeFixture C-PMID '' 'Research Intake Safety' 'Kim' '2026' '123'));$p=Promote-RapFixture $c C-PMID;$i=Resolve-RapCanonicalPaperIdentity $c.Store $p;$i.Pmid='999';Gate-F F03 ((Get-RapIntakeThrown {Get-RapPreZoteroDedupDecision $c.Store $p $i})-match'IDENTITY_BINDING_MISMATCH') 'PMID substitution blocked'
$ca=New-RapIntakeContext -Results @((New-RapIntakeFixture C-A));$pa=Promote-RapFixture $ca C-A;$ia=Resolve-RapCanonicalPaperIdentity $ca.Store $pa;$cb=New-RapIntakeContext -Results @((New-RapIntakeFixture C-B '10.1234/RAP.002' 'Second Paper'));$pb=Promote-RapFixture $cb C-B;Gate-F F04 ((Get-RapIntakeThrown {Get-RapPreZoteroDedupDecision $cb.Store $pb $ia})-match'CANDIDATE_SUBSTITUTION') 'Candidate identity artifact replay blocked'
Gate-F F05 (Identity-Attack-F {$args[0].ProjectId='PR999'}) 'Project identity artifact replay blocked'
$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) '' $true;$p=Promote-RapFixture $c;$r=Invoke-RapResearchIntakeDecision $c.Store $p;Gate-F F06 ($r.Decision.Decision-cne'CREATE_CANDIDATE'-and$c.Store.Counters.ZoteroCreateDecision-eq0) 'LOOKUP_REQUIRED bypass blocked'
Gate-F F07 (Lookup-Attack-F TIMEOUT) 'TIMEOUT bypass blocked'
Gate-F F08 (Lookup-Attack-F PARTIAL) 'PARTIAL bypass blocked'
Gate-F F09 (Reuse-Attack-F {$args[0].ZoteroItemId='Z-EVIL'}) 'ZoteroItemId substitution blocked'
Gate-F F10 (Reuse-Attack-F {$args[0].ZoteroLibraryContext='LIBRARY-EVIL'}) 'library/context substitution blocked'
Gate-F F11 (Reuse-Attack-F {$args[0].CanonicalTargetIdentity='doi:10.9999/evil'}) 'canonical target substitution blocked'
$c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].Decision='REUSE_EXISTING';$c.Store.Decisions['C-001'].State='REUSE_EXISTING';Gate-F F12 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'CREATE to REUSE substitution blocked'
$e=Existing-F;$c=New-RapIntakeContext @($e) @($e);$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].Decision='CREATE_CANDIDATE';$c.Store.Decisions['C-001'].State='CREATE_CANDIDATE';Gate-F F13 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'REUSE to CREATE substitution blocked'

$temp=Join-Path ([IO.Path]::GetTempPath()) ('ri-turn-f-'+[guid]::NewGuid().ToString('N'));New-Item $temp -ItemType Directory|Out-Null
try{
    $db=Join-Path $temp 'fresh-envelope.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].Reason='FORGED';Save-RapResearchIntakeStore $c.Store|Out-Null;$s=Open-RapResearchIntakeStore $db;Gate-F F14 ((Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']).Decision.Decision-ceq'BLOCKED') 'stale decision plus fresh envelope blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].CandidateId='C-B';Gate-F F15 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'Candidate A decision to Candidate B blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.Decisions['C-001'].ProjectId='PR999';Gate-F F16 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'Project A decision to Project B blocked'
    $db=Join-Path $temp 'restart-identity.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.IdentityResults['C-001'].CanonicalKey='doi:10.9999/evil';Save-RapResearchIntakeStore $c.Store|Out-Null;$s=Open-RapResearchIntakeStore $db;Gate-F F17 ((Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']})-match'IDENTITY_BINDING_MISMATCH') 'restart plus changed identity blocked'
    $db=Join-Path $temp 'restart-lookup.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$s=Open-RapResearchIntakeStore $db;$null=Invoke-RapResearchIntakeReadOnlyLookup $s TIMEOUT;Gate-F F18 ((Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']).Decision.Decision-ceq'BLOCKED') 'restart plus changed lookup blocked'
    $db=Join-Path $temp 'restart-target.db';$e=Existing-F;$c=New-RapIntakeContext @($e) @($e) @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$s=Open-RapResearchIntakeStore $db;$s.Decisions['C-001'].ZoteroItemId='Z-EVIL';Save-RapResearchIntakeStore $s|Out-Null;$s=Open-RapResearchIntakeStore $db;Gate-F F19 ((Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']).Decision.Decision-ceq'BLOCKED') 'restart plus changed target blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$c.Store.Audit.RemoveAt([int]$d.RevalidationSequence-1);Gate-F F20 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'missing revalidation audit blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$a=@($c.Store.Audit|Where-Object{$_.Sequence-eq$d.DecisionAuditSequence})[0];$a.Data.DecisionId='DEC-WRONG';Gate-F F21 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'wrong-decision audit evidence blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$c.Store.Audit=$null;$thrown=Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $c.Store $p};Gate-F F22 (($thrown-ne'')-and$c.Store.Decisions.Count-eq0-and$c.Store.Counters.ZoteroCreateDecision-eq0) 'audit write failure cannot authorize decision'
    $db=Join-Path $temp 'legacy.db';$c=New-RapIntakeContext @() @() @((New-RapIntakeFixture)) $db;[Rap.NativeSqlite]::Execute($db,"UPDATE ResearchIntakeStore SET SchemaVersion=3 WHERE StoreId='PRIMARY';",5000);Gate-F F23 ((Get-RapIntakeThrown {Open-RapResearchIntakeStore $db})-match'SCHEMA_UNSUPPORTED') 'legacy schema authority escalation blocked'
    $db=Join-Path $temp 'combined.db';$e=Existing-F;$c=New-RapIntakeContext @($e) @($e) @((New-RapIntakeFixture)) $db;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$c.Store.IdentityResults['C-001'].CanonicalKey='doi:10.9999/evil';$c.Store.Decisions['C-001'].ZoteroItemId='Z-EVIL';Save-RapResearchIntakeStore $c.Store|Out-Null;$s=Open-RapResearchIntakeStore $db;$out=Get-RapIntakeThrown {Invoke-RapResearchIntakeDecision $s $s.Promotions['C-001']};Gate-F F24 ($out-match'IDENTITY_BINDING_MISMATCH') 'combined identity target envelope substitution blocked'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$identityAudit=@($c.Store.Audit|Where-Object{$_.Event-ceq'IDENTITY_RESOLVED'})[0];$identityAudit.Event='IDENTITY_AUDIT_REMOVED';Gate-F F25 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'missing identity audit blocks replay'
    $c=New-RapIntakeContext;$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$lookupAudit=@($c.Store.Audit|Where-Object{$_.Event-ceq'READ_ONLY_LOOKUP_EXECUTED'})[0];$lookupAudit.Event='LOOKUP_AUDIT_REMOVED';Gate-F F26 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'missing lookup audit blocks replay'
    $e=Existing-F;$c=New-RapIntakeContext @($e) @($e);$p=Promote-RapFixture $c;$null=Invoke-RapResearchIntakeDecision $c.Store $p;$d=$c.Store.Decisions['C-001'];$a=@($c.Store.Audit|Where-Object{$_.Sequence-eq$d.DecisionAuditSequence})[0];$a.Data.ZoteroItemId='';Gate-F F27 ((Invoke-RapResearchIntakeDecision $c.Store $p).Decision.Decision-ceq'BLOCKED') 'missing target audit blocks REUSE replay'
}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}

Write-Host "SPR-015 Turn F independent probes: PASS=$script:Pass FAIL=$script:Fail TOTAL=$($script:Pass+$script:Fail)"
if($script:Fail-gt0){Write-Host 'TURN_F_FINAL_GATE_PROBES=FAIL';exit 1}
Write-Host 'TURN_F_FINAL_GATE_PROBES=PASS'
