Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot '../ResearchAutomation.Local/modules/Queue.psm1') -Force
function ConvertTo-RapSynthesisStoreText {param($Value)[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(($Value|ConvertTo-Json -Depth 60 -Compress)))}
function ConvertFrom-RapSynthesisStoreText {param([string]$Value)if([string]::IsNullOrWhiteSpace($Value)){return $null};[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Value))|ConvertFrom-Json -Depth 60}
function Assert-RapSynthesisToken {param([string]$Value,[string]$Name)if($Value -notmatch '^[A-Za-z0-9._:-]+$'){throw "Invalid $Name for Synthesis store."}}
function Initialize-RapSynthesisStore { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath,[int]$BusyTimeoutMilliseconds=5000) $p=Queue\Initialize-RapQueue $DatabasePath $BusyTimeoutMilliseconds;$sql="CREATE TABLE IF NOT EXISTS SynthesisState(Id INTEGER PRIMARY KEY CHECK(Id=1),Payload TEXT NOT NULL,UpdatedUtc TEXT NOT NULL);CREATE TABLE IF NOT EXISTS SynthesisAudit(Id INTEGER PRIMARY KEY AUTOINCREMENT,OperationId TEXT NOT NULL,Payload TEXT NOT NULL,CreatedUtc TEXT NOT NULL);";[Rap.NativeSqlite]::Execute($p,$sql,$BusyTimeoutMilliseconds);$p }
function New-RapSynthesisSqliteDependencies { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath,[int]$BusyTimeoutMilliseconds=5000) $path=Initialize-RapSynthesisStore $DatabasePath $BusyTimeoutMilliseconds;$encode=${function:ConvertTo-RapSynthesisStoreText};$decode=${function:ConvertFrom-RapSynthesisStoreText};$assert=${function:Assert-RapSynthesisToken};$read={ $v=[Rap.NativeSqlite]::Scalar($path,'SELECT Payload FROM SynthesisState WHERE Id=1;',$BusyTimeoutMilliseconds);if($v){& $decode $v}else{[pscustomobject]@{Specifications=@();Runs=@()}} }.GetNewClosure();$write={param($state)$payload=& $encode $state;$now=[DateTimeOffset]::UtcNow.ToString('o');[Rap.NativeSqlite]::Execute($path,"INSERT OR REPLACE INTO SynthesisState(Id,Payload,UpdatedUtc) VALUES(1,'$payload','$now');",$BusyTimeoutMilliseconds)}.GetNewClosure();$getOperation={param($id)& $assert $id OperationId;$v=[Rap.NativeSqlite]::Scalar($path,"SELECT Payload FROM Operations WHERE OperationKey='$id' AND Type='Synthesis';",$BusyTimeoutMilliseconds);& $decode $v}.GetNewClosure();$saveOperation={param($o)& $assert ([string]$o.OperationId) OperationId;$payload=& $encode $o;$now=[DateTimeOffset]::UtcNow.ToString('o');$id=[string]$o.OperationId;$status=[string]$o.State;[Rap.NativeSqlite]::Execute($path,"INSERT OR IGNORE INTO Operations(OperationKey,Type,Payload,Status,CreatedUtc,UpdatedUtc) VALUES('$id','Synthesis','$payload','$status','$now','$now');UPDATE Operations SET Payload='$payload',Status='$status',UpdatedUtc='$now' WHERE OperationKey='$id' AND Type='Synthesis';",$BusyTimeoutMilliseconds)}.GetNewClosure();$saveSpec={param($spec)$state=& $read;$items=@($state.Specifications|Where-Object{!($_.AnalysisId -eq $spec.AnalysisId -and $_.ConfigurationHash -eq $spec.ConfigurationHash)})+@($spec);& $write ([pscustomobject]@{Specifications=$items;Runs=@($state.Runs)})}.GetNewClosure();$saveRun={param($run)$state=& $read;$items=@($state.Runs|Where-Object RunId -ne $run.RunId)+@($run);& $write ([pscustomobject]@{Specifications=@($state.Specifications);Runs=$items})}.GetNewClosure();$audit={param($a)$payload=& $encode $a;$now=[DateTimeOffset]::UtcNow.ToString('o');$id=[string]$a.OperationId;[Rap.NativeSqlite]::Execute($path,"INSERT INTO SynthesisAudit(OperationId,Payload,CreatedUtc) VALUES('$id','$payload','$now');",$BusyTimeoutMilliseconds)}.GetNewClosure();[pscustomobject]@{GetOperation=$getOperation;SaveOperation=$saveOperation;SaveSpecification=$saveSpec;SaveRun=$saveRun;AppendAudit=$audit;ReadState=$read} }
function Get-RapSynthesisFixtureSnapshot { [CmdletBinding()]param([Parameter(Mandatory)][string]$DatabasePath,[int]$BusyTimeoutMilliseconds=5000)$null=Initialize-RapSynthesisStore $DatabasePath $BusyTimeoutMilliseconds;$v=[Rap.NativeSqlite]::Scalar([IO.Path]::GetFullPath($DatabasePath),'SELECT Payload FROM SynthesisState WHERE Id=1;',$BusyTimeoutMilliseconds);if($v){ConvertFrom-RapSynthesisStoreText $v}else{[pscustomobject]@{Specifications=@();Runs=@()}} }
Export-ModuleMember -Function Initialize-RapSynthesisStore,New-RapSynthesisSqliteDependencies,Get-RapSynthesisFixtureSnapshot
