Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

$script:RapAnalysisHumanFields=@('CriticalAppraisal','ReviewerInterpretation','ReviewerMemo','ScientificConclusion','ResearcherInterpretation')

function ConvertTo-RapAnalysisCanonical { param($Value) if($null -eq $Value){return $null};if($Value -is [Collections.IDictionary]){$o=[ordered]@{};foreach($k in @($Value.Keys|ForEach-Object{[string]$_}|Sort-Object)){$o[$k]=ConvertTo-RapAnalysisCanonical $Value[$k]};return $o};if($Value -is [Management.Automation.PSCustomObject]){$o=[ordered]@{};foreach($p in @($Value.PSObject.Properties|Sort-Object Name)){$o[$p.Name]=ConvertTo-RapAnalysisCanonical $p.Value};return $o};if($Value -is [Collections.IEnumerable] -and $Value -isnot [string]){return @($Value|ForEach-Object{ConvertTo-RapAnalysisCanonical $_})};$Value }
function Get-RapAnalysisHash { param([Parameter(Mandatory)]$Value) $json=(ConvertTo-RapAnalysisCanonical $Value)|ConvertTo-Json -Depth 60 -Compress;[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($json))).ToLowerInvariant() }
function Get-RapAnalysisValue { param($Object,[string]$Name) if($null -eq $Object){return $null};if($Object -is [Collections.IDictionary]){foreach($k in $Object.Keys){if([string]$k -ieq $Name){return $Object[$k]}};return $null};$p=$Object.PSObject.Properties|Where-Object Name -IEQ $Name|Select-Object -First 1;if($p){$p.Value}else{$null} }
function Assert-RapNoAnalysisHumanWrite { param($Value,[string]$Path='Analysis') if($null -eq $Value){return};if($Value -is [Collections.IEnumerable] -and $Value -isnot [string] -and $Value -isnot [Collections.IDictionary]){$i=0;foreach($item in $Value){Assert-RapNoAnalysisHumanWrite $item "$Path[$i]";$i++};return};$entries=if($Value -is [Collections.IDictionary]){$Value.GetEnumerator()|ForEach-Object{[pscustomobject]@{Name=[string]$_.Key;Value=$_.Value}}}else{$Value.PSObject.Properties};foreach($e in @($entries)){if($script:RapAnalysisHumanFields -icontains $e.Name){throw "HUMAN_OWNED_FIELD_BLOCKED: $Path.$($e.Name)"};if($e.Value -is [Collections.IDictionary] -or $e.Value -is [Management.Automation.PSCustomObject]){Assert-RapNoAnalysisHumanWrite $e.Value "$Path.$($e.Name)"}} }

function New-RapAnalysisSpecification {
    [CmdletBinding()]param([Parameter(Mandatory)][ValidatePattern('^AN-[A-Za-z0-9._-]+$')][string]$AnalysisId,[Parameter(Mandatory)][ValidatePattern('^PR\d{3}$')][string]$ProjectId,[string]$Name='Primary synthesis',[ValidateSet('FIXED','RANDOM')][string]$Model='RANDOM',[ValidateSet('DL','NONE')][string]$Estimator='DL',[ValidateSet('NONE','ONE_EFFECT','AGGREGATE','MULTILEVEL','RVE')][string]$DependencyStrategy='NONE',[string[]]$EligibleEffectTypes=@('Hedges_g'),[string[]]$ModeratorSelection=@(),[string]$OutcomeScope='CONFIRMED',[string]$ComparisonScope='CONFIRMED',[string]$TimePointScope='CONFIRMED',[string]$EngineVersion='spr-009.1')
    if($Model -eq 'FIXED' -and $Estimator -ne 'NONE'){throw 'FIXED_MODEL_ESTIMATOR_MUST_BE_NONE'};if($Model -eq 'RANDOM' -and $Estimator -eq 'NONE'){throw 'RANDOM_MODEL_ESTIMATOR_REQUIRED'}
    $scientific=[ordered]@{ProjectId=$ProjectId;Name=$Name;OutcomeScope=$OutcomeScope;ComparisonScope=$ComparisonScope;TimePointScope=$TimePointScope;EligibleEffectTypes=@($EligibleEffectTypes);Model=$Model;Estimator=$Estimator;HeterogeneityMethod='Q_I2_TAU2';ModeratorSelection=@($ModeratorSelection);DependencyStrategy=$DependencyStrategy;SensitivityRules=@('LEAVE_ONE_OUT');PublicationBiasDiagnostics=@('FUNNEL_DATA');EngineVersion=$EngineVersion}
    [pscustomobject]@{AnalysisId=$AnalysisId;ProjectId=$ProjectId;Name=$Name;Model=$Model;Estimator=$Estimator;DependencyStrategy=$DependencyStrategy;EligibleEffectTypes=@($EligibleEffectTypes);ModeratorSelection=@($ModeratorSelection);OutcomeScope=$OutcomeScope;ComparisonScope=$ComparisonScope;TimePointScope=$TimePointScope;EngineVersion=$EngineVersion;ConfigurationHash=(Get-RapAnalysisHash $scientific);ScientificConfiguration=[pscustomobject]$scientific;CreatedAt=[DateTimeOffset]::UtcNow.ToString('o');Ownership='RESEARCHER_SPECIFIED'}
}

function Get-RapHedgesG {
    [CmdletBinding()]param([double]$MeanTreatment,[double]$MeanControl,[ValidateRange(2,[int]::MaxValue)][int]$NTreatment,[ValidateRange(2,[int]::MaxValue)][int]$NControl,[ValidateScript({$_ -gt 0})][double]$SdTreatment,[ValidateScript({$_ -gt 0})][double]$SdControl)
    $df=$NTreatment+$NControl-2;$pooled=[Math]::Sqrt((($NTreatment-1)*$SdTreatment*$SdTreatment+($NControl-1)*$SdControl*$SdControl)/$df);$d=($MeanTreatment-$MeanControl)/$pooled;$j=1-(3/(4*($NTreatment+$NControl)-9));$g=$j*$d;$variance=(($NTreatment+$NControl)/($NTreatment*$NControl))+($g*$g/(2*$df));[pscustomobject]@{EffectValue=$g;Variance=$variance;StandardError=[Math]::Sqrt($variance);Method='HEDGES_G_FROM_GROUP_SUMMARIES';FormulaVersion='1.0';SourceInputs=[pscustomobject]@{MeanTreatment=$MeanTreatment;MeanControl=$MeanControl;SdTreatment=$SdTreatment;SdControl=$SdControl;NTreatment=$NTreatment;NControl=$NControl}}
}

function New-RapAnalysisDataset {
    [CmdletBinding()]param([Parameter(Mandatory)]$Specification,[Parameter(Mandatory)][object[]]$Records)
    Assert-RapNoAnalysisHumanWrite $Records
    $rows=[Collections.Generic.List[object]]::new();$ids=@{}
    foreach($r in $Records){
        if([string](Get-RapAnalysisValue $r 'ConfirmationState') -ne 'RESEARCHER_CONFIRMED'){throw 'RESEARCHER_CONFIRMATION_REQUIRED'}
        foreach($name in @('ProjectId','LibraryId','MetaCodingId','EffectSizeId','OutcomeId','ComparisonId','TimePointId','DependencyGroupId','EffectSizeType','ProvenanceReference')){if([string]::IsNullOrWhiteSpace([string](Get-RapAnalysisValue $r $name))){throw "ANALYSIS_INPUT_REQUIRED: $name"}}
        if([string]$r.ProjectId -ne [string]$Specification.ProjectId){throw 'PROJECT_SCOPE_MISMATCH'};if($ids.ContainsKey([string]$r.EffectSizeId)){throw 'DUPLICATE_EFFECT_ID'};$ids[[string]$r.EffectSizeId]=$true
        if([string]$r.EvidenceStatus -eq 'CONFLICTING_EVIDENCE'){throw 'UNRESOLVED_CONFLICT'};if([string]$r.EvidenceStatus -notin @('SUPPORTED','INFERRED')){throw 'EVIDENCE_NOT_ANALYSIS_READY'}
        if([string]$r.EffectSizeType -notin @($Specification.EligibleEffectTypes)){throw 'UNSUPPORTED_EFFECT_CONVERSION'}
        $n=[int]$r.SampleSize;if($n -le 0){throw 'INVALID_SAMPLE_SIZE'};$variance=[double]$r.Variance;if($variance -le 0 -or [double]::IsNaN($variance)){throw 'INVALID_VARIANCE'}
        $effect=[double]$r.EffectValue;$action=[string](Get-RapAnalysisValue $r 'DirectionAction');if([string]::IsNullOrWhiteSpace($action)){$action='NONE'}
        if($action -eq 'REQUIRED'){throw 'DIRECTION_HARMONIZATION_REQUIRED'};if($action -eq 'REVERSE'){if(-not [bool](Get-RapAnalysisValue $r 'DirectionConfirmed')){throw 'DIRECTION_CONFIRMATION_REQUIRED'};$analysisEffect=-$effect}else{$analysisEffect=$effect}
        $row=[pscustomobject]@{AnalysisId=$Specification.AnalysisId;ProjectId=$r.ProjectId;LibraryId=$r.LibraryId;MetaCodingId=$r.MetaCodingId;EffectSizeId=$r.EffectSizeId;OutcomeId=$r.OutcomeId;ComparisonId=$r.ComparisonId;StudyArmId=(Get-RapAnalysisValue $r 'StudyArmId');MeasurementId=(Get-RapAnalysisValue $r 'MeasurementId');TimePointId=$r.TimePointId;DependencyGroupId=$r.DependencyGroupId;EffectSizeType=$r.EffectSizeType;EffectOrigin=$r.EffectOrigin;OriginalEffect=$effect;AnalysisEffect=$analysisEffect;Variance=$variance;StandardError=[Math]::Sqrt($variance);SampleSize=$n;Moderator=(Get-RapAnalysisValue $r 'Moderator');DirectionAction=$action;InclusionStatus='INCLUDED';ProvenanceReference=$r.ProvenanceReference;StatisticalInputs=(Get-RapAnalysisValue $r 'StatisticalInputs');Transformation=(Get-RapAnalysisValue $r 'Transformation');ConfirmationState=$r.ConfirmationState}
        $rows.Add($row)
    }
    $dependencies=@($rows|Group-Object DependencyGroupId|Where-Object Count -gt 1|ForEach-Object Name)
    if($dependencies.Count -gt 0 -and $Specification.DependencyStrategy -eq 'NONE'){throw 'DEPENDENCY_STRATEGY_REQUIRED'}
    $canonical=@($rows|Sort-Object LibraryId,EffectSizeId);[pscustomobject]@{AnalysisId=$Specification.AnalysisId;ProjectId=$Specification.ProjectId;Rows=$canonical;DatasetHash=(Get-RapAnalysisHash $canonical);DependencyGroups=$dependencies;DependencyStrategy=$Specification.DependencyStrategy;BuiltAt=[DateTimeOffset]::UtcNow.ToString('o');ProductionWrite='DISABLED'}
}

function Invoke-RapPooledModel { param([object[]]$Rows,[string]$Model,[string]$Estimator)
    if($Rows.Count -lt 1){throw 'NO_ELIGIBLE_EFFECTS'};$sumW=0.0;$sumWY=0.0;foreach($r in $Rows){$w=1/[double]$r.Variance;$sumW+=$w;$sumWY+=$w*[double]$r.AnalysisEffect};$fixed=$sumWY/$sumW;$q=0.0;$sumW2=0.0;foreach($r in $Rows){$w=1/[double]$r.Variance;$q+=$w*[Math]::Pow(([double]$r.AnalysisEffect-$fixed),2);$sumW2+=$w*$w};$df=$Rows.Count-1;$i2=if($q -gt 0){[Math]::Max(0.0,[double](($q-$df)/$q*100))}else{0.0};$tau2=0.0;if($Model -eq 'RANDOM'){$c=$sumW-($sumW2/$sumW);if($c -gt 0){$tau2=[Math]::Max(0.0,[double](($q-$df)/$c))}};$rw=0.0;$rwy=0.0;foreach($r in $Rows){$w=1/([double]$r.Variance+$tau2);$rw+=$w;$rwy+=$w*[double]$r.AnalysisEffect};$pooled=$rwy/$rw;$se=[Math]::Sqrt(1/$rw);[pscustomobject]@{PooledEstimate=$pooled;StandardError=$se;ConfidenceLow=$pooled-1.96*$se;ConfidenceHigh=$pooled+1.96*$se;Q=$q;I2=$i2;Tau2=$tau2;Model=$Model;Estimator=$Estimator}
}

function Invoke-RapSynthesis {
    [CmdletBinding()]param([Parameter(Mandatory)]$Specification,[Parameter(Mandatory)]$Dataset,[string]$OperationId,[Parameter(Mandatory)]$Dependencies,[ValidateSet('Fixture')][string]$Mode='Fixture')
    foreach($n in @('GetOperation','SaveOperation','SaveSpecification','SaveRun','AppendAudit')){if($Dependencies.$n -isnot [scriptblock]){throw "SYNTHESIS_DEPENDENCY_REQUIRED: $n"}}
    if($Dataset.ProjectId -ne $Specification.ProjectId -or $Dataset.AnalysisId -ne $Specification.AnalysisId){throw 'ANALYSIS_CONTEXT_MISMATCH'}
    if([string]::IsNullOrWhiteSpace($OperationId)){$OperationId='SYNTH-'+(Get-RapAnalysisHash ([ordered]@{Dataset=$Dataset.DatasetHash;Config=$Specification.ConfigurationHash;Engine=$Specification.EngineVersion})).Substring(0,24)}
    $payloadHash=Get-RapAnalysisHash ([ordered]@{DatasetHash=$Dataset.DatasetHash;ConfigurationHash=$Specification.ConfigurationHash;EngineVersion=$Specification.EngineVersion})
    $existing=& $Dependencies.GetOperation $OperationId;if($existing -and $existing.PayloadHash -ne $payloadHash){throw 'PAYLOAD_CONFLICT'};if($existing -and $existing.State -eq 'COMPLETED'){return [pscustomobject]@{Status='ALREADY_COMPLETED';Run=$existing.Run;ProductionWrite='DISABLED'}}
    & $Dependencies.SaveOperation ([pscustomobject]@{OperationId=$OperationId;PayloadHash=$payloadHash;State='PREPARED';Run=$null})
    & $Dependencies.SaveSpecification $Specification
    $stats=Invoke-RapPooledModel @($Dataset.Rows) $Specification.Model $Specification.Estimator;$runId="$($Specification.AnalysisId):$($Specification.ConfigurationHash.Substring(0,12)):$($Dataset.DatasetHash.Substring(0,12))"
    $lineage=@($Dataset.Rows|ForEach-Object{[pscustomobject]@{Source="EFFECT_SIZE:$($_.EffectSizeId)|$($_.ProjectId)";Relation='GENERATED_RESULT_FROM';Target="ANALYSIS_RESULT:$runId";ProjectId=$_.ProjectId;Evidence=$_.ProvenanceReference;StatisticalInputs=$_.StatisticalInputs}})
    $run=[pscustomobject]@{RunId=$runId;AnalysisId=$Specification.AnalysisId;ProjectId=$Specification.ProjectId;StudyCount=@($Dataset.Rows|Select-Object -ExpandProperty LibraryId -Unique).Count;EffectCount=@($Dataset.Rows).Count;PooledEstimate=$stats.PooledEstimate;StandardError=$stats.StandardError;ConfidenceLow=$stats.ConfidenceLow;ConfidenceHigh=$stats.ConfidenceHigh;Model=$stats.Model;Estimator=$stats.Estimator;Tau2=$stats.Tau2;Q=$stats.Q;I2=$stats.I2;ConfigurationHash=$Specification.ConfigurationHash;InputDatasetHash=$Dataset.DatasetHash;EngineVersion=$Specification.EngineVersion;GeneratedAt=[DateTimeOffset]::UtcNow.ToString('o');DependencyStrategy=$Specification.DependencyStrategy;Lineage=$lineage;Warnings=@();ScientificInterpretation=$null;ProductionWrite='DISABLED'}
    & $Dependencies.SaveRun $run;& $Dependencies.SaveOperation ([pscustomobject]@{OperationId=$OperationId;PayloadHash=$payloadHash;State='COMPLETED';Run=$run});& $Dependencies.AppendAudit ([pscustomobject]@{AnalysisId=$Specification.AnalysisId;OperationId=$OperationId;ProjectId=$Specification.ProjectId;ConfigurationHash=$Specification.ConfigurationHash;DatasetHash=$Dataset.DatasetHash;EngineVersion=$Specification.EngineVersion;Status='COMPLETED';Timestamp=[DateTimeOffset]::UtcNow.ToString('o');Exclusions=@();Transformations=@($Dataset.Rows|Where-Object DirectionAction -ne 'NONE'|Select-Object EffectSizeId,DirectionAction)})
    [pscustomobject]@{Status='COMPLETED';Run=$run;ProductionWrite='DISABLED'}
}

function Invoke-RapSubgroupAnalysis { [CmdletBinding()]param($Specification,$Dataset,[string]$ModeratorName) if($Specification.ModeratorSelection -notcontains $ModeratorName){throw 'MODERATOR_NOT_APPROVED'};$groups=@();foreach($g in @($Dataset.Rows|Group-Object { [string](Get-RapAnalysisValue $_.Moderator $ModeratorName) })){$s=Invoke-RapPooledModel @($g.Group) $Specification.Model $Specification.Estimator;$groups+=[pscustomobject]@{Moderator=$ModeratorName;Group=$g.Name;Count=$g.Count;PooledEstimate=$s.PooledEstimate}};[pscustomobject]@{AnalysisId=$Specification.AnalysisId;Moderator=$ModeratorName;Groups=$groups;AutomaticSelection=$false} }
function Invoke-RapSensitivityAnalysis { [CmdletBinding()]param($Specification,$Dataset,[ValidateSet('LEAVE_ONE_OUT')][string]$Method='LEAVE_ONE_OUT') $runs=@();foreach($row in $Dataset.Rows){$remaining=@($Dataset.Rows|Where-Object EffectSizeId -ne $row.EffectSizeId);if($remaining.Count -gt 0){$s=Invoke-RapPooledModel $remaining $Specification.Model $Specification.Estimator;$runs+=[pscustomobject]@{ParentAnalysisId=$Specification.AnalysisId;Method=$Method;ExcludedEffectSizeId=$row.EffectSizeId;PooledEstimate=$s.PooledEstimate;Timestamp=[DateTimeOffset]::UtcNow.ToString('o')}}};[pscustomobject]@{ParentAnalysisId=$Specification.AnalysisId;Runs=$runs;PrimaryOverwritten=$false} }
function Get-RapPublicationBiasDiagnostic { [CmdletBinding()]param($Dataset) [pscustomobject]@{AnalysisId=$Dataset.AnalysisId;Diagnostic='FUNNEL_DATA';Points=@($Dataset.Rows|ForEach-Object{[pscustomobject]@{EffectSizeId=$_.EffectSizeId;Effect=$_.AnalysisEffect;StandardError=$_.StandardError}});Interpretation=$null;ResearcherInterpretationRequired=$true} }

Export-ModuleMember -Function New-RapAnalysisSpecification,Get-RapHedgesG,New-RapAnalysisDataset,Invoke-RapSynthesis,Invoke-RapSubgroupAnalysis,Invoke-RapSensitivityAnalysis,Get-RapPublicationBiasDiagnostic
