Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot '../ResearchAutomation.Reconciliation.psd1') -Force
function Copy-RapRec($v){$v|ConvertTo-Json -Depth 60|ConvertFrom-Json -Depth 60}
function New-RapRecExpected { [pscustomobject]@{LibraryId='LIB:L000001';ProjectId='PR001';EvidenceComplete=$true;IdentityAmbiguous=$false;Records=@([pscustomobject]@{RecordId='DERIVED:1';Value=[pscustomobject]@{Status='CURRENT';Version=2};Ownership='AUTO_OWNED';Evidence=[pscustomobject]@{Source='fixture';Version=2}},[pscustomobject]@{RecordId='HUMAN:1';Value='keep';Ownership='HUMAN_OWNED';Evidence=[pscustomobject]@{Source='researcher'}},[pscustomobject]@{RecordId='CONFIRMED:1';Value='confirmed';Ownership='ResearcherConfirmed';Evidence=[pscustomobject]@{Source='researcher';Confirmed=$true}})} }
function New-RapRecActual { $s=Copy-RapRec (New-RapRecExpected);$s.Records[0].Value.Version=1;$s.Records[0].Value.Status='STALE';$s }
function New-RapRecMemory($snapshot){$clone={param($v)$v|ConvertTo-Json -Depth 60|ConvertFrom-Json -Depth 60}.GetNewClosure();$state=[pscustomobject]@{Snapshot=&$clone $snapshot;Operations=@{};Audits=[Collections.Generic.List[object]]::new()};$d=[pscustomobject]@{ReadSnapshot={param($l,$p)if($state.Snapshot.LibraryId-eq$l-and$state.Snapshot.ProjectId-eq$p){&$clone $state.Snapshot}else{$null}}.GetNewClosure();GetOperation={param($id)if($state.Operations.ContainsKey($id)){$state.Operations[$id]}else{$null}}.GetNewClosure();CommitRecovery={param($s,$o,$a)$state.Snapshot=&$clone $s;$state.Operations[$o.OperationId]=$o;$state.Audits.Add($a)}.GetNewClosure()};[pscustomobject]@{State=$state;Dependencies=$d}}
function Get-RapRecPlan($expected,$actual,[string]$id='RC-OP'){$diff=Compare-RapIntegritySnapshot $expected $actual;$decision=New-RapReconciliationDecision $diff;$plan=New-RapRecoveryPlan $diff $decision $id;[pscustomobject]@{Diff=$diff;Decision=$decision;Plan=$plan}}
function Get-RapThrown([scriptblock]$Action){try{&$Action;''}catch{$_.Exception.Message}}
