. (Join-Path $PSScriptRoot 'TestHarness.ps1')
$script:N=0
function A([string]$id,[bool]$ok,[string]$message){$script:N++;if(!$ok){throw "$id failed: $message"};Write-Host "$id PASS $message"}
function E([scriptblock]$script){try{&$script;$null}catch{$_.Exception.Message}}
function Reload-RapCw {Import-Module (Join-Path $PSScriptRoot '../ResearchAutomation.ProductionReadiness.psd1') -Force}
$script:TempRoot=Join-Path ([IO.Path]::GetTempPath()) ('rap-cw-gate-probes-'+[guid]::NewGuid());[void](New-Item -ItemType Directory -Path $script:TempRoot);$script:DbPath=Join-Path $script:TempRoot 'controlled-write.db'
function P([string]$operationId,[hashtable]$override=@{}){$parameters=@{OperationId=$operationId;LibraryId='LIB:L000003';ProjectId='PR003';TargetSystem='Notion';TargetObject='page-L000003';TargetObjectType='MetadataRecord';TargetField='RAP_Status';Action='UPDATE';BatchCount=1;BeforeValue='draft';ProposedValue='reviewed';Reason='SPR-014 Gate probe';Ownership='RAP_OWNED';ExpectedVersion='7';IdentityStatus='MATCHED';CanonicalLibraryIdPresent=$true;IdentityAmbiguous=$false;PdfIdentityVerified=$true;OwnershipConflict=$false;StaleState=$false;RollbackInfo='Restore RAP_Status from persisted audit.';DatabasePath=$script:DbPath};foreach($key in $override.Keys){$parameters[$key]=$override[$key]};New-RapControlledWritePlan @parameters}
function ApproveTestPlan($plan){$request=New-RapControlledWriteApprovalRequest $plan;Approve-RapControlledWritePlan $plan $request 'gate-human-reviewer' HUMAN 'SPR-014 Gate approval'}
function Adapter($plan,$approval,[hashtable]$extra=@{}){$parameters=@{Plan=$plan;Approval=$approval;InitialFields=@{RAP_Status='draft'};Version=7};foreach($key in $extra.Keys){$parameters[$key]=$extra[$key]};New-RapControlledWriteFixtureAdapter @parameters}
try{
    $p=P G01;A G01 ((E {Invoke-RapControlledWritePilot $p $null ([pscustomobject]@{})})-match'HUMAN_APPROVAL_REQUIRED') 'approval absent blocked'
    $p1=P G02A;$x1=ApproveTestPlan $p1;$p2=P G02B;$x2=ApproveTestPlan $p2;$a2=Adapter $p2 $x2;A G02 ((E {Invoke-RapControlledWritePilot $p2 $x1 $a2})-match'APPROVAL_BINDING_MISMATCH') 'different Operation_ID approval blocked'
    $p=P G03;$x=ApproveTestPlan $p;$a=Adapter $p $x;$p.ProposedValue='tampered';A G03 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'PLAN_TAMPERED') 'payload changed after approval blocked'
    $p=P G04;$x=ApproveTestPlan $p;$a=Adapter $p $x;$p.TargetObject='page-other';A G04 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'PLAN_TAMPERED') 'target changed after approval blocked'
    $p=P G05;$x=ApproveTestPlan $p;$a=Adapter $p $x;$null=Invoke-RapControlledWritePilot $p $x $a;$r=Invoke-RapControlledWritePilot $p $x $a;A G05 ($r.Status-eq'ALREADY_COMPLETED'-and$r.MutationCount-eq0) 'approval/idempotent replay safe'
    $p=P G06;$q=New-RapControlledWriteApprovalRequest $p;A G06 ((E {Approve-RapControlledWritePlan $p $q 'rap-ai-agent' AI 'self'})-match'SELF_APPROVAL_BLOCKED') 'AI self approval blocked'
    $p=P G07;$fake=[pscustomobject]@{PSTypeName='Rap.ControlledWriteApproval';ApprovalId=[guid]::NewGuid().ToString();OperationId='G07';DatabasePath=$script:DbPath};A G07 ((E {New-RapControlledWriteFixtureAdapter -Plan $p -Approval $fake -InitialFields @{RAP_Status='draft'} -Version 7})-match'UNTRUSTED_CONTROLLED_WRITE_APPROVAL') 'forged approval blocked'
    $p=P G08;$x=ApproveTestPlan $p;$a=Adapter $p $x;$p.OperationId='G08-FORGED';A G08 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'PLAN_TAMPERED') 'forged Operation_ID blocked'
    $p=P G09;$x=ApproveTestPlan $p;$a=New-RapControlledWriteFixtureAdapter -Plan $p -Approval $x -InitialFields @{RAP_Status='changed'} -Version 8;A G09 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'STALE_CONTROLLED_WRITE_PLAN') 'stale value/version blocked'
    $p=P G10;$x=ApproveTestPlan $p;$a=Adapter $p $x @{TimeoutAfterApply=$true};$first=Invoke-RapControlledWritePilot $p $x $a;$retry=Invoke-RapControlledWritePilot $p $x $a;A G10 ($first.Status-eq'PARTIAL_FAILURE'-and$retry.Status-eq'RECOVERY_REQUIRED'-and$retry.PersistedState-eq'APPLIED'-and$retry.MutationCount-eq0) 'partial failure retry blocks automatic mutation'
    $p=P G11;$x=ApproveTestPlan $p;$a=Adapter $p $x @{CurrentProjectId='PR999'};A G11 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'IDENTITY_CHANGED') 'cross-project mutation blocked'
    $p=P G12;$x=ApproveTestPlan $p;$a=Adapter $p $x @{CurrentLibraryId='LIB:L000004'};A G12 ((E {Invoke-RapControlledWritePilot $p $x $a})-match'IDENTITY_CHANGED') 'canonical Library_ID target binding enforced'
    $p=P G13;$x=ApproveTestPlan $p;$a=Adapter $p $x;$null=Invoke-RapControlledWritePilot $p $x $a;Reload-RapCw;$r=Invoke-RapControlledWritePilot $p $x $a;A G13 ($r.Status-eq'ALREADY_COMPLETED'-and$r.MutationCount-eq0) 'restart/replay loads persisted VERIFIED operation'
    $p=P G14;$x=ApproveTestPlan $p;$a=Adapter $p $x;$s=Get-RapControlledWriteFixtureState $a;$required=@('LibraryId','ProjectId','TargetSystem','TargetObject','TargetField','Ownership','IdentityStatus','CanonicalLibraryIdPresent','PdfIdentityVerified');A G14 (@($required|Where-Object{$_-notin$s.PSObject.Properties.Name}).Count-eq0) 'fresh ownership and identity revalidation surface present'
    if($script:N-ne14){throw "Expected 14 Gate probes, got $script:N"};Write-Host 'SPR-014 independent Gate probes: 14/14 PASS; failures: 0'
}finally{Remove-Item -LiteralPath $script:TempRoot -Recurse -Force}
